/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol BBObserverDelegate <NSObject>
@optional
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed playLightsAndSirens:(BOOL)sirens withReply:(id)reply;
- (id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;
- (CGSize)observer:(id)observer composedAttachmentSizeForType:(int)type thumbnailWidth:(float)width height:(float)height key:(id)key;
- (void)observer:(id)observer modifyBulletin:(id)bulletin;
- (void)observer:(id)observer modifyBulletin:(id)bulletin forFeed:(unsigned)feed;
- (id)observer:(id)observer multipleThumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
- (void)observer:(id)observer noteAlertBehaviorOverrideStateChanged:(unsigned)changed;
- (void)observer:(id)observer noteAlertBehaviorOverridesChanged:(unsigned)changed;
- (void)observer:(id)observer noteInvalidatedBulletinIDs:(id)ids;
- (void)observer:(id)observer noteSectionParametersChanged:(id)changed forSectionID:(id)sectionID;
- (void)observer:(id)observer noteServerConnectionStateChanged:(BOOL)changed;
- (void)observer:(id)observer noteServerReceivedResponseForBulletin:(id)bulletin;
- (void)observer:(id)observer purgeReferencesToBulletinID:(id)bulletinID;
- (void)observer:(id)observer removeBulletin:(id)bulletin;
- (void)observer:(id)observer removeBulletin:(id)bulletin forFeed:(unsigned)feed;
- (id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
- (void)observer:(id)observer updateSectionInfo:(id)info;
- (void)observer:(id)observer updateSectionInfo:(id)info inCategory:(int)category;
- (void)observer:(id)observer updateSectionOrder:(id)order;
- (void)observer:(id)observer updateSectionOrder:(id)order forCategory:(int)category;
- (void)observer:(id)observer updateSectionOrderRule:(int)rule;
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
- (BOOL)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(id)observer;
@end

