/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol BSSettingDescriptionProvider <NSObject>
@optional
- (id)keyDescriptionForSetting:(unsigned)setting;
- (id)settings:(id)settings keyDescriptionForSetting:(unsigned)setting;
- (id)settings:(id)settings valueDescriptionForFlag:(int)flag object:(id)object ofSetting:(unsigned)setting;
- (id)valueDescriptionForFlag:(int)flag object:(id)object ofSetting:(unsigned)setting;
@end

