/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol FBApplicationPlaceholderObserver <NSObject>
@optional
- (void)placeholderCancellabilityDidChange:(id)placeholderCancellability;
- (void)placeholderDidChangeSignificantly:(id)placeholder;
- (void)placeholderInstallPhaseDidChange:(id)placeholderInstallPhase;
- (void)placeholderInstallStateDidChange:(id)placeholderInstallState;
- (void)placeholderPausabilityDidChange:(id)placeholderPausability;
- (void)placeholderPercentCompleteDidChange:(id)placeholderPercentComplete;
@end

