/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol ISPlayerViewDelegate <NSObject>
@optional
- (id)irisPlayerView:(id)view delegateForGestureRecognizer:(id)gestureRecognizer;
- (id)irisPlayerViewViewHostingGestureRecognizers:(id)recognizers;
- (void)playerViewDidEndVisualPlayback:(id)playerView;
- (void)playerViewDidPlaybackVideoAssetToEnd:(id)playerView;
- (void)playerViewIsInteractingDidChange:(id)playerViewIsInteracting;
- (void)playerViewPlaybackStateDidChange:(id)playerViewPlaybackState;
- (void)playerViewWillBeginVisualPlayback:(id)playerView;
@end

