/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MPAVRoutingControllerDelegate <NSObject>
@optional
- (void)routingController:(id)controller didFailToPickRouteWithError:(id)error;
- (void)routingControllerAvailableRoutesDidChange:(id)routingControllerAvailableRoutes;
- (void)routingControllerExternalScreenTypeDidChange:(id)routingControllerExternalScreenType;
@end

