/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PGPictureInPictureControllerDelegate <NSObject>
@optional
- (void)pictureInPictureController:(id)pictureController didCreatePictureInPictureViewController:(id)pictureViewController;
- (void)pictureInPictureController:(id)pictureController willDestroyPictureInPictureViewController:(id)pictureViewController;
@end

