/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PKPaymentServiceDelegate <NSObject>
@optional
- (void)contactlessInterfaceDidDismissForPassesWithUniqueIdentifiers:(id)contactlessInterface fromSource:(int)source;
- (void)contactlessInterfaceDidDismissFromSource:(int)contactlessInterface;
- (void)contactlessInterfaceDidPresentFromSource:(int)contactlessInterface;
- (void)didUpdateDefaultPaymentPassWithUniqueIdentifier:(id)uniqueIdentifier;
- (void)passWithUniqueIdentifier:(id)uniqueIdentifier didReceiveValueAddedServiceTransaction:(id)transaction;
- (void)paymentDeviceDidEnterFieldWithProperties:(id)paymentDevice;
- (void)paymentDeviceDidExitField;
- (void)paymentPassWithUniqueIdentifier:(id)uniqueIdentifier didEnableMessageService:(BOOL)service;
- (void)paymentPassWithUniqueIdentifier:(id)uniqueIdentifier didEnableTransactionService:(BOOL)service;
- (void)paymentPassWithUniqueIdentifier:(id)uniqueIdentifier didReceiveMessage:(id)message;
- (void)paymentPassWithUniqueIdentifier:(id)uniqueIdentifier didReceiveTransaction:(id)transaction;
- (void)paymentPassWithUniqueIdentifier:(id)uniqueIdentifier didRemoveTransactionWithIdentifier:(id)identifier;
- (void)paymentServiceReceivedInterruption;
@end

