/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBAlertDelegate <NSObject>
- (void)alert:(id)alert didChangeStatusBarVisibility:(BOOL)visibility;
- (void)alert:(id)alert requestsBackgroundStyleChangeWithAnimationFactory:(id)animationFactory;
- (void)alertDidChangeOccluding:(id)alert;
- (void)alertDidChangeOrientationEventsEnabled:(id)alert;
- (void)alertIsReadyToBeDeactivated:(id)beDeactivated;
- (void)alertIsReadyToBeRemovedFromView:(id)view;
- (void)alertWantsToForceWallpaperTunnelUpdate:(id)forceWallpaperTunnelUpdate;
- (void)alertWillDismiss:(id)alert;
- (int)defaultInterfaceOrientationForPresentationOfAlert:(id)alert;
- (BOOL)defaultShouldAutorotateForAlert:(id)aDefault;
- (unsigned)defaultSupportedInterfaceOrientationsForAlert:(id)alert;
@end

