/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBDisplay.h"

@class NSMutableDictionary, SBAlertWindow, SBAlertDisplay;

@interface SBAlert : SBDisplay {
	SBAlertDisplay *_display;
	NSMutableDictionary *_dictionary;
	SBAlertWindow *_deferredAlertWindow;
}
+ (id)alertWindow;
+ (void)registerForAlerts;
+ (void)test;
- (BOOL)activate;
- (id)alertDisplayViewWithSize:(CGSize)size;
- (CGRect)alertWindowRect;
- (BOOL)allowsInCallStatusBar;
- (BOOL)allowsStackingOfAlert:(id)alert;
- (double)animateInDuration;
- (BOOL)animatesDismissal;
- (float)autoDimTime;
- (BOOL)deactivate;
- (void)dealloc;
- (void)didAnimateLockKeypadIn;
- (void)didAnimateLockKeypadOut;
- (void)didFinishAnimatingIn;
- (void)didFinishAnimatingOut;
- (id)display;
- (BOOL)displaysAboveLock;
- (float)finalAlpha;
- (id)objectForKey:(id)key;
- (void)removeFromView;
- (void)setDisplay:(id)display;
- (void)setObject:(id)object forKey:(id)key;
- (int)statusBarMode;
- (int)statusBarOrientation;
- (void)tearDownAlertWindow:(id)window;
- (BOOL)undimsDisplay;
@end

