/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBUIAnimationStepping.h"


__attribute__((visibility("hidden")))
@interface SBAnimationStepper : XXUnknownSuperclass <SBUIAnimationStepping> {
	BSAnimationSettings *_animationSettings;
	NSMutableSet *_views;
	NSMutableSet *_finishedAnimatingViews;
	CADisplayLink *_displayLink;
	id _completion;
	float _percentage;
	BOOL _invalidated;
	BOOL _completed;
	BOOL _finishingForward;
	BOOL _finishingBackward;
	float _finishSpeed;
	BOOL _animatingToStepPercent;
	double _animatedSteppingTimestamp;
	double _animatedSteppingStartPercent;
	double _animatedSteppingTargetPercent;
	double _finishBackwardTimestamp;
	double _finishBackwardDuration;
	float _finishBackwardPercentage;
	double _beganFinishingTimestamp;
	double _duration;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign, nonatomic) double duration;
@property(assign, nonatomic) float finishSpeed;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) float stepPercentage;
@property(readonly, assign, nonatomic, getter=isStepped) BOOL stepped;
@property(readonly, assign) Class superclass;
@property(readonly, retain, nonatomic) NSArray *views;
- (id)init;
- (id)initWithAnimationSettings:(id)animationSettings;
- (void)_checkForCompletion;
- (void)_displayLinkFired:(id)fired;
- (void)_displayLinkFiredForBackwardToStart:(id)start;
- (void)_interruptFinish;
- (void)_setStepPercentage:(float)percentage;
- (void)_updateAnimationSteppingTarget:(float)target;
- (void)animateToStepPercentage:(float)stepPercentage;
- (void)animationDidStop:(id)animation finished:(BOOL)finished;
- (void)dealloc;
- (id)descriptionBuilderWithMultilinePrefix:(id)multilinePrefix;
- (id)descriptionWithMultilinePrefix:(id)multilinePrefix;
- (void)finishSteppingBackwardToStart;
- (void)finishSteppingBackwardToStartWithCompletion:(id)completion;
- (void)finishSteppingForwardToEnd;
- (void)finishSteppingForwardToEndWithCompletion:(id)completion;
- (void)invalidate;
- (void)startSteppingAnimationsInView:(id)view;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
@end

