/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBAppSwitcherRemoteAlertContextHostWrapperView : XXUnknownSuperclass <SBAppSwitcherPageContentView> {
	UIView *_containerView;
	SBWallpaperEffectView *_wallpaperView;
	UIView<SBAppSwitcherCacheVended> *_fakeStatusBarView;
	SBAppSwitcherStatusBarViewCache *_statusBarCache;
	SBRemoteAlertAdapter *_remoteAlert;
	FBWindowContextHostManager *_contextHostManager;
	UIView<FBWindowContextAppearance> *_contextHostView;
	int _orientation;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int orientation;
@property(readonly, assign) Class superclass;
- (id)initWithFrame:(CGRect)frame remoteAlert:(id)alert statusBarCache:(id)cache contextHostManager:(id)manager;
- (void)_layoutStatusBar;
- (CGAffineTransform)_rotationTransformForOrientation:(int)orientation;
- (void)dealloc;
- (void)didMoveToSuperview;
- (void)layoutSubviews;
- (void)prepareToBecomeVisibleIfNecessary;
- (void)respondToBecomingInvisibleIfNecessary;
- (CGSize)sizeThatFits:(CGSize)fits;
@end

