/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAppToAppTransitionView.h"


__attribute__((visibility("hidden")))
@interface SBAppShuffleView : SBAppToAppTransitionView {
}
- (void)beginTransition;
- (void)endTransition;
@end

