/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIFullscreenAnimationViewDelegate.h"
#import "SBUIAnimationController.h"

@class SBAppToAppTransitionView;

__attribute__((visibility("hidden")))
@interface SBAppToAppTransitionController : SBUIAnimationController <SBUIFullscreenAnimationViewDelegate> {
	SBAppToAppTransitionView *_transitionView;
	BOOL _requiresHostView;
	BOOL _dismissBanner;
}
@property(retain, nonatomic) SBAppToAppTransitionView *transitionView;
+ (id)_transitionWindow;
- (id)initWithActivatingApp:(id)activatingApp deactivatingApp:(id)app;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)_cancelAnimation;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (void)_setHidden:(BOOL)hidden;
- (void)_startAnimation;
- (void)appTransitionView:(id)view animationWillStartWithDuration:(double)animation afterDelay:(double)delay;
- (void)appTransitionViewAnimationDidStop:(id)appTransitionViewAnimation;
- (void)dealloc;
@end

