/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAppSwitcherSettings : XXUnknownSuperclass {
	BOOL _clipStatusBarArea;
	BOOL _useTitleOpacityPrototypeSettings;
	BOOL _useOrbGesture;
	BOOL _forceDrivesInitialProgress;
	BOOL _playInitialHaptic;
	BOOL _playCommitHaptic;
	BOOL _canPop;
	int _switcherStyle;
	int _deckSwitcherForegroundWallpaperStyle;
	int _deckSwitcherBackgroundWallpaperStyle;
	float _deckSwitcherForegroundDarkeningFactor;
	float _deckSwitcherBackgroundDarkeningFactor;
	float _deckSwitcherForegroundSaturationDeltaFactor;
	float _deckSwitcherBackgroundSaturationDeltaFactor;
	float _deckSwitcherForegroundBlurRadius;
	float _deckSwitcherBackgroundBlurRadius;
	float _insertMass;
	float _insertStiffness;
	float _insertDamping;
	float _translateProgress;
	float _minTranslation;
	float _maxPopTranslation;
	float _commitToNextAppTranslation;
	float _nextAppPopScale;
	float _orbGestureRegionMax;
	float _panHysteresis;
	float _dismissAnimationMass;
	float _dismissAnimationStiffness;
	float _dismissAnimationDamping;
	float _dismissAnimationEpsilon;
	float _presentAnimationMass;
	float _presentAnimationStiffness;
	float _presentAnimationDamping;
	float _additionalThrowDisplacement;
	int _simplicityOptions;
	SBAnimationSettings *_dosidoAnimationSettings;
	double _aExpLayoutCoeff;
	double _bExpLayoutCoeff;
	double _depthPadding;
	double _titleOpacityACoeff;
	double _titleOpacityBCoeff;
	double _titleOpacityCCoeff;
	double _titleOpacityDCoeff;
}
@property(assign) double aExpLayoutCoeff;
@property(assign) float additionalThrowDisplacement;
@property(assign) double bExpLayoutCoeff;
@property(assign) BOOL canPop;
@property(assign) BOOL clipStatusBarArea;
@property(assign) float commitToNextAppTranslation;
@property(assign) float deckSwitcherBackgroundBlurRadius;
@property(assign) float deckSwitcherBackgroundDarkeningFactor;
@property(assign) float deckSwitcherBackgroundSaturationDeltaFactor;
@property(assign) int deckSwitcherBackgroundWallpaperStyle;
@property(assign) float deckSwitcherForegroundBlurRadius;
@property(assign) float deckSwitcherForegroundDarkeningFactor;
@property(assign) float deckSwitcherForegroundSaturationDeltaFactor;
@property(assign) int deckSwitcherForegroundWallpaperStyle;
@property(assign) double depthPadding;
@property(assign) float dismissAnimationDamping;
@property(assign) float dismissAnimationEpsilon;
@property(assign) float dismissAnimationMass;
@property(assign) float dismissAnimationStiffness;
@property(retain) SBAnimationSettings *dosidoAnimationSettings;
@property(assign) BOOL forceDrivesInitialProgress;
@property(assign) float insertDamping;
@property(assign) float insertMass;
@property(assign) float insertStiffness;
@property(assign) float maxPopTranslation;
@property(assign) float minTranslation;
@property(assign) float nextAppPopScale;
@property(assign) float orbGestureRegionMax;
@property(assign) float panHysteresis;
@property(assign) BOOL playCommitHaptic;
@property(assign) BOOL playInitialHaptic;
@property(assign) float presentAnimationDamping;
@property(assign) float presentAnimationMass;
@property(assign) float presentAnimationStiffness;
@property(assign) int simplicityOptions;
@property(assign) int switcherStyle;
@property(assign) double titleOpacityACoeff;
@property(assign) double titleOpacityBCoeff;
@property(assign) double titleOpacityCCoeff;
@property(assign) double titleOpacityDCoeff;
@property(assign) float translateProgress;
@property(assign) BOOL useOrbGesture;
@property(assign) BOOL useTitleOpacityPrototypeSettings;
+ (id)settingsControllerModule;
- (void)setDefaultValues;
- (BOOL)shouldSimplifyForOptions:(int)options;
@end

