/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBApplicationUninstallationOperation : NSOperation {
	NSString *_bundleIdentifier;
}
- (id)initWithBundleIdentifier:(id)bundleIdentifier;
- (void)dealloc;
- (void)main;
@end

