/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBApplicationShortcutServerDelegate <NSObject>
- (id)appliationShortcutServer:(id)server dynamicShortcutItemsForBundleIdentifier:(id)bundleIdentifier;
- (void)appliationShortcutServer:(id)server setDynamicShortcutItems:(id)items bundleIdentifier:(id)identifier;
@end

