/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "FBApplicationLibraryObserver.h"


__attribute__((visibility("hidden")))
@interface SBApplicationLibraryObserver : XXUnknownSuperclass <FBApplicationLibraryObserver> {
	FBApplicationLibrary *_appLibrary;
	NSMutableDictionary *_placeholdersByBundleID;
	NSHashTable *_applicationObservers;
	NSHashTable *_placeholderObservers;
}
@property(readonly, retain, nonatomic) FBApplicationLibrary *appLibrary;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, copy, nonatomic) NSArray *placeholders;
@property(readonly, assign) Class superclass;
+ (id)sharedInstance;
- (id)init;
- (void)_addObserver:(id)observer table:(id)table;
- (void)_removeObserver:(id)observer table:(id)table;
- (void)addApplicationLifecycleObserver:(id)observer;
- (void)addPlaceholderLifecycleObserver:(id)observer;
- (void)applicationLibrary:(id)library didAddApplications:(id)applications;
- (void)applicationLibrary:(id)library didAddPlaceholders:(id)placeholders;
- (void)applicationLibrary:(id)library didCancelPlaceholders:(id)placeholders;
- (void)applicationLibrary:(id)library didDemoteApplications:(id)applications;
- (void)applicationLibrary:(id)library didRemoveApplications:(id)applications;
- (void)applicationLibrary:(id)library didReplaceApplications:(id)applications withApplications:(id)applications3;
- (void)applicationLibrary:(id)library networkUsageDidChange:(BOOL)networkUsage;
- (void)dealloc;
- (void)notePlaceholderCancelled:(id)cancelled;
- (void)removeApplicationLifecycleObserver:(id)observer;
- (void)removePlaceholderLifecycleObserver:(id)observer;
@end

