/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBNewsstandItemIconViewBase.h"


__attribute__((visibility("hidden")))
@interface SBAppSwitcherNewsstandItemIconView : SBNewsstandItemIconViewBase {
}
+ (Class)_labelImageParametersClassForIcon:(id)icon location:(int)location;
- (id)initWithFrame:(CGRect)frame;
- (id)_superviewForAccessoryView;
- (void)_updateLabelVisibility;
- (CGRect)defaultFrameForProgressBar;
- (void)positionCloseBoxOfType:(int)type;
- (void)positionIconImageView;
- (void)setShadowsHidden:(BOOL)hidden;
@end

