/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAppRepairTransaction : XXUnknownSuperclass {
	NSSet *_appInfos;
	NSMutableSet *_repairRequests;
}
@property(readonly, copy, nonatomic) NSSet *appInfos;
- (id)initWithApplicationInfos:(id)applicationInfos;
- (void)_begin;
- (BOOL)_canBeInterrupted;
- (void)_completeRequest:(id)request success:(BOOL)success error:(id)error;
- (void)_didComplete;
- (void)_evaluateCompletion;
- (void)_startAppRepairs;
- (void)dealloc;
@end

