/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "LSBestAppSuggestionManagerDelegate.h"


__attribute__((visibility("hidden")))
@interface SBAppSuggestionManager : XXUnknownSuperclass <LSBestAppSuggestionManagerDelegate> {
	LSBestAppSuggestionManager *_suggestionManager;
	LSBestAppSuggestion *_currentBestSuggestion;
	BOOL _isListeningForBestSuggestion;
	BOOL _screenOnDueToUserEvent;
	BOOL _lookingForEvent;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
+ (id)sharedInstance;
- (id)init;
- (void)_createSuggestionManager;
- (void)_destroySuggestionManager;
- (void)_evaluateSuggestionUpdates:(id)updates;
- (void)_handleInitialSpringBoardLaunch;
- (void)_listenForNotifications;
- (void)_nextUserEventOccured:(id)occured;
- (void)_screenDidDim:(id)_screen;
- (void)_screenDidUndim:(id)_screen;
- (void)_setAppSuggestionUpdatesEnabled:(BOOL)enabled;
- (void)_stopListeningForNotifications;
- (id)allCurrentlySuggestedApps;
- (void)bestAppSuggestionChanged:(id)changed;
- (id)currentSuggestedApp;
- (void)dealloc;
- (void)noteActivatingForAppSuggestion:(id)appSuggestion fromSource:(int)source;
- (void)noteNotActivatingForAppSuggestion:(id)appSuggestion;
- (void)startFetchingPayloadForAppSuggestion:(id)appSuggestion;
@end

