/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBAppPagerDelegate
- (id)appPager:(id)pager viewForItem:(id)item;
@optional
- (void)appPagerFinishedScrolling:(id)scrolling;
@end

