/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBAppSwitcherPeopleDataSource <NSObject>
@property(assign, nonatomic) id<SBAppSwitcherPeopleDataSourceConsumer> consumer;
- (void)cachedMonogramImageForPersonID:(int)personID ofSize:(float)size generatingIfNecessaryWithResult:(id)result;
- (id)contactItemForIndexPath:(id)indexPath;
- (id)existingCachedMonogramImageForPersonID:(int)personID ofSize:(float)size outIsMask:(BOOL *)mask;
- (unsigned)numberOfContactsInSection:(unsigned)section;
- (unsigned)numberOfSections;
- (id)optionalEmptyPlaceholderStringForSection:(unsigned)section;
- (void)purgeCaches;
- (id)silhouetteMonogramOfSize:(float)size;
- (id)titleForSection:(unsigned)section;
- (void)updateIfNecessary;
@end

