/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBAppSwitcherRemoteAlertCellView : SBSwitcherWallpaperPageContentView {
	SBDisplayItem *_displayItem;
	SBOrientationTransformWrapperView *_portraitContentWrapper;
	SBOrientationTransformWrapperView *_rotatingContentWrapper;
	FBSceneHostManager *_contextHostManager;
	UIView *_alertContentViewWrapper;
	SBFakeStatusBarView *_fakeStatusBar;
	UIView *_contentView;
	SBRemoteAlertAdapter *_remoteAlert;
	BOOL _remoteAlertHasCustomWallpaperStyle;
	BOOL _remoteAlertRemoteTunnelingWasActive;
	int _remoteAlertWallpaperStyle;
}
@property(readonly, copy, nonatomic) SBDisplayItem *displayItem;
@property(assign, nonatomic) BOOL remoteAlertHasCustomWallpaperStyle;
@property(assign, nonatomic) BOOL remoteAlertRemoteTunnelingWasActive;
@property(assign, nonatomic) int remoteAlertWallpaperStyle;
- (id)initWithFrame:(CGRect)frame remoteAlert:(id)alert displayItem:(id)item;
- (void)_addStatusBar;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (void)_updateBackgroundStyle;
- (void)_updateHosting;
- (void)dealloc;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (void)hostAlertWithManager:(id)manager;
- (void)installAlertInViewController:(id)viewController;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void *)context;
- (void)prepareToBecomeVisibleIfNecessary;
- (void)setAlert:(id)alert;
- (void)setOrientation:(int)orientation;
- (CGSize)sizeThatFits:(CGSize)fits;
- (void)viewDismissing:(id)dismissing withInteraction:(BOOL)interaction andInitialProgress:(float)progress forTransitionRequest:(id)transitionRequest;
- (void)viewPresenting:(id)presenting withInteraction:(BOOL)interaction andInitialProgress:(float)progress forTransitionRequest:(id)transitionRequest;
@end

