/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAppSwitcherRemoteAlertManager : XXUnknownSuperclass {
	SBAppSwitcherRemoteAlertSet *_remoteAlerts;
}
+ (id)sharedInstance;
- (void)addPlaceholderForIdentifier:(id)identifier;
- (void)addRemoteAlert:(id)alert;
- (id)currentRemoteAlerts;
- (void)dealloc;
- (void)removePlaceholderForIdentifier:(id)identifier;
- (void)removeRemoteAlert:(id)alert;
@end

