/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSArray, NSString;

@interface SBAssistantGuideSectionModel : XXUnknownSuperclass {
	NSString *_title;
	NSMutableArray *_phrases;
}
@property(retain, nonatomic) NSArray *phrases;
@property(retain, nonatomic) NSString *title;
- (id)init;
- (void)dealloc;
@end

