/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class AFUIUtteranceView;

@interface SBAssistantGuideSectionListCell : XXUnknownSuperclass {
	AFUIUtteranceView *_bubbleView;
	CGSize _currentSize;
}
- (id)initWithReuseIdentifier:(id)reuseIdentifier;
- (float)currentHeight;
- (void)dealloc;
- (void)layoutSubviews;
- (void)setPhrase:(id)phrase;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (CGSize)sizeThatFits:(CGSize)fits;
@end

