/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBAssistantGuideModel : XXUnknownSuperclass {
	NSMutableArray *_domains;
}
@property(readonly, assign) NSArray *allDomains;
- (id)init;
- (void)_loadAllDomains;
- (void)dealloc;
@end

