/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBAssistantViewDelegate <NSObject>
- (void)assistantView:(id)view madeRequest:(id)request;
- (BOOL)assistantViewAffectsMagicPocket:(int)pocket;
- (void)assistantViewAnimatedIn:(id)anIn;
- (void)assistantViewAnimatedOut:(id)anOut;
- (float)assistantViewAudioLevel:(id)level;
- (void)assistantViewSearchScrolledToView:(id)view;
@end

