/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_SBUIWidgetHost.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol SBWidgetViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBAttributionWrapperViewController : XXUnknownSuperclass <_SBUIWidgetHost> {
	_SBUIWidgetViewController *_attributionViewController;
	id<SBWidgetViewControllerDelegate> _widgetDelegate;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
@property(assign, nonatomic) id<SBWidgetViewControllerDelegate> widgetDelegate;
+ (id)_loadAttributionAppBundle;
+ (id)_newAttributionViewController;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void)dealloc;
- (void)invalidatePreferredViewSize;
- (void)requestLaunchOfURL:(id)url;
- (void)requestPresentationOfViewController:(id)viewController presentationStyle:(int)style context:(id)context completion:(id)completion;
- (void)setVisibleWidgetsIDs:(id)ids;
- (void)viewDidLoad;
@end

