/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAutoPurgingImageView : XXUnknownSuperclass {
	id _block;
}
- (id)initWithImageNamed:(id)imageNamed;
- (id)_initWithImageBlock:(id)imageBlock andInitialLoadBlock:(id)block;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)setImage:(id)image;
@end

