/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBAwayCardListItem : XXUnknownSuperclass {
	SBSCardItem *_cardItem;
}
@property(copy, nonatomic) SBSCardItem *cardItem;
- (void)dealloc;
- (BOOL)inertWhenLocked;
- (id)sortDate;
@end

