/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIButton, UIImageView;

@interface SBAwayBuddyBackgroundView : XXUnknownSuperclass {
	UIImageView *_linenView;
	UIImageView *_titleView;
	UIButton *_infoButton;
}
- (id)initWithFrame:(CGRect)frame;
- (void)layoutSubviews;
- (void)setInfoButtonAlpha:(float)alpha;
@end

