/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBAwayDateView : UIView {
	NSTimer *_dateTimer;
	TPLCDTextView *_timeLabel;
	TPLCDTextView *_titleLabel;
	NSString *_title;
	SBAwayMediaControlsView *_controlsView;
}
- (id)initWithFrame:(CGRect)frame;
- (id)controlsView;
- (void)dealloc;
- (BOOL)isShowingControls;
- (id)labelWithFontSize:(float)fontSize origin:(CGPoint)origin;
- (id)labelWithFontSize:(float)fontSize origin:(CGPoint)origin fontName:(const char *)name;
- (void)movedToSuperview:(id)superview;
- (void)removeFromSuperview;
- (void)setAlpha:(float)alpha;
- (void)setIsShowingControls:(BOOL)controls;
- (void)setTitle:(id)title;
- (void)updateClock;
- (void)updateClockFormat;
- (void)updateLabels;
@end

