/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBBannerTapGestureRecognizer : XXUnknownSuperclass {
	id _touchesBeganBlock;
	id _touchesEndedBlock;
}
@property(copy, nonatomic) id touchesBeganBlock;
@property(copy, nonatomic) id touchesEndedBlock;
- (void)dealloc;
- (void)touchesBegan:(id)began withEvent:(id)event;
- (void)touchesEnded:(id)ended withEvent:(id)event;
@end

