/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBBookmarkIcon : SBLeafIcon {
	UIWebClip *_webClip;
}
@property(retain, nonatomic) UIWebClip *webClip;
- (id)initWithWebClip:(id)webClip;
- (BOOL)allowsUninstall;
- (void)completeUninstall;
- (id)copyWithZone:(NSZone *)zone;
- (void)dealloc;
- (id)displayName;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)generateIconImage:(int)image;
- (void)launch;
@end

