/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBBTSSPAlertItem : SBAlertItem {
	id _delegate;
	NSString *_name;
	NSNumber *_number;
}
@property(assign, nonatomic) id delegate;
- (id)initWithName:(id)name andComparison:(id)comparison;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
- (void)dealloc;
- (void)dismiss:(int)dismiss;
@end

