/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUIBannerSource.h"
#import "BBObserverDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBBulletinBannerController : XXUnknownSuperclass <BBObserverDelegate, SBUIBannerSource> {
	NSMutableArray *_bulletinQueue;
	BBObserver *_observer;
	NSMutableSet *_sectionIDsToPend;
}
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (id)init;
- (void)_configureBBObserver;
- (unsigned)_indexOfQueuedBulletinID:(id)queuedBulletinID;
- (void)_queueBulletin:(id)bulletin;
- (void)_removeBulletin:(id)bulletin;
- (void)_removeNextBulletinIfNecessary;
- (BOOL)_replaceBulletin:(id)bulletin;
- (void)dealloc;
- (id)dequeueNextBannerItem;
- (id)newBannerViewForItem:(id)item;
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
- (id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;
- (void)observer:(id)observer modifyBulletin:(id)bulletin;
- (void)observer:(id)observer removeBulletin:(id)bulletin;
- (id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
- (void)observer:(id)observer updateSectionInfo:(id)info;
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
- (id)peekNextBannerItem;
- (void)removeAllBannerItems;
- (void)showTestBanner;
@end

