/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBBulletinSoundController : XXUnknownSuperclass <BBObserverDelegate, SBBulletinBusyClient> {
	BBObserver *_observer;
	NSMutableArray *_blockQueue;
	NSMutableDictionary *_playingSounds;
	BOOL _deviceIsLocked;
	BOOL _quietModeEnabled;
}
+ (id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (id)init;
- (void)_configureBBObserver;
- (void)_enqueueBlock:(id)block;
- (void)_hardwareButtonPressed:(id)pressed;
- (BOOL)_shouldHonorPlaySoundRequestForBulletin:(id)bulletin;
- (void)bulletinWindowStoppedBeingBusy;
- (void)dealloc;
- (void)killSoundForBulletin:(id)bulletin;
- (void)killSounds;
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
- (void)observer:(id)observer noteAlertBehaviorOverridesChanged:(unsigned)changed;
- (void)observer:(id)observer removeBulletin:(id)bulletin;
- (BOOL)playSoundForBulletin:(id)bulletin;
@end

