/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBBulletinModalAlert : XXUnknownSuperclass {
	BBBulletin *_bulletin;
	NSArray *_buttons;
	NSArray *_bulletinButtonIndices;
	BOOL _playedSound;
	SBBulletinModalAlert *_superseded;
	NSArray *_actions;
}
@property(retain, nonatomic) NSArray *actions;
@property(retain, nonatomic) NSArray *bulletinButtonIndices;
@property(retain, nonatomic) NSArray *buttons;
- (id)initWithBulletin:(id)bulletin;
- (id)initWithBulletin:(id)bulletin supersededAlert:(id)alert;
- (id)_actionForAlertViewButtonIndex:(int)alertViewButtonIndex;
- (id)_actionsFromBulletin;
- (id)_actionsWithOptions;
- (void)_configureSheetWithBulletinActions;
- (void)_configureSheetWithBulletinButtons;
- (id)_defaultAction;
- (id)_defaultActions;
- (id)_defaultAppearance;
- (id)_dismissAction;
- (id)_dismissAppearance;
- (void)_handleAction:(id)action atIndex:(int)index;
- (void)_handleActionGroup:(id)group;
- (id)_optionsAppearance;
- (id)_snoozeAction;
- (id)_snoozeAppearance;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (BOOL)allowMenuButtonDismissal;
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
- (void)dealloc;
- (void)didPresentAlertView:(id)view;
- (void)dismiss:(int)dismiss;
- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (void)willDeactivateForReason:(int)reason;
- (void)willPresentAlertView:(id)view;
@end

