/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDosidoAnimator.h"


__attribute__((visibility("hidden")))
@interface SBCarDosidoAnimator : SBDosidoAnimator {
	SBStarkScreenController *_screenController;
}
- (id)initWithParentView:(id)parentView fromOrientation:(int)orientation starkScreenController:(id)controller;
- (void)_animateDosidoWithFactory:(id)factory completion:(id)completion;
- (void)_cleanupDosido;
- (void)_prepareDosido;
- (void)dealloc;
@end

