/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBCalendarIconContentsView : XXUnknownSuperclass {
	NSDateFormatter *_dateFormatter;
	NSString *_dayNumberFormat;
}
- (id)initWithFrame:(CGRect)frame;
- (void)dealloc;
- (void)drawRect:(CGRect)rect;
- (void)updateLocale;
@end

