/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RadiosPreferencesDelegate.h"
#import "SBControlCenterSectionViewController.h"
#import "SBUIControlCenterButtonDelegate.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBCCSettingsSectionController : SBControlCenterSectionViewController <SBUIControlCenterButtonDelegate, RadiosPreferencesDelegate> {
	NSMutableDictionary *_buttonsByID;
	BOOL _settingSupported[6];
	RadiosPreferences *_airplaneModeController;
	BBSettingsGateway *_settingsGateway;
	BOOL _dndEnabled;
	int _dndStatus;
	BluetoothManager *_btManager;
}
+ (Class)viewClass;
- (id)init;
- (void)_addButtonForSetting:(int)setting;
- (id)_buttonForSetting:(int)setting;
- (BOOL)_getAirplaneMode;
- (BOOL)_getBluetooth;
- (BOOL)_getDND;
- (BOOL)_getMuted;
- (BOOL)_getOrientationLocked;
- (BOOL)_getWifi;
- (id)_identifierForSetting:(int)setting;
- (void)_initAirplaneMode;
- (void)_initBluetooth;
- (void)_initDND;
- (void)_initMute;
- (void)_initOrientationLock;
- (void)_initWifi;
- (void)_setAirplaneModeEnabled:(BOOL)enabled;
- (void)_setBluetoothEnabled:(BOOL)enabled;
- (void)_setDNDEnabled:(BOOL)enabled updateServer:(BOOL)server;
- (void)_setDNDStatus:(int)status;
- (void)_setMuted:(BOOL)muted;
- (void)_setOrientationLocked:(BOOL)locked;
- (void)_setWifiEnabled:(BOOL)enabled;
- (void)_tearDownAirplaneMode;
- (void)_tearDownBluetooth;
- (void)_tearDownDND;
- (void)_tearDownMute;
- (void)_tearDownOrientationLock;
- (void)_tearDownWifi;
- (void)_updateBluetoothState;
- (void)_updateMuteButtonState;
- (void)_updateOrientationLockButtonState;
- (void)_updateWifiButtonState;
- (void)airplaneModeChanged;
- (void)buttonTapped:(id)tapped;
- (CGSize)contentSizeForOrientation:(int)orientation;
- (void)dealloc;
- (void)noteSettingsDidUpdate:(id)noteSettings;
- (id)sectionIdentifier;
- (id)view;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillLayoutSubviews;
@end

