/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */


@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBCCFlashlightSetting : SBCCSettingModule {
	AVFlashlight *_flashlight;
	NSObject<OS_dispatch_queue> *_flashlightQueue;
	BOOL _stayWarm;
	BOOL _flashlightOn;
}
@property(assign, nonatomic, getter=isFlashlightOn) BOOL flashlightOn;
+ (id)displayName;
+ (id)identifier;
+ (BOOL)isSupported:(int)supported;
- (void)_deviceBlockStateDidChangeNotification:(id)_deviceBlockState;
- (BOOL)_enableTorch:(BOOL)torch;
- (void)_featureLockStateDidChangeNotification:(id)_featureLockState;
- (id)_imageNameForState:(int)state section:(int)section;
- (id)_settingImageNameForState:(int)state;
- (id)_shortcutImageNameForState:(int)state;
- (void)_tearDown;
- (BOOL)_toggleState;
- (void)_updateFlashlightPowerState;
- (void)_updateState;
- (void)activate;
- (id)aggdKey;
- (void)cooldown;
- (void)deactivate;
- (void)dealloc;
- (id)displayName;
- (id)glyphImageForState:(int)state section:(int)section;
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void *)context;
- (id)statusUpdate;
- (id)unavailableText;
- (void)warmup;
@end

