/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBCCAirStuffSectionController : SBControlCenterSectionViewController <MPAVRoutingControllerDelegate, UIPopoverControllerDelegate, SFAirDropDiscoveryControllerDelegate, SFAirDropDiscoveryAlertControllerDelegate> {
	SBCCButtonLikeSectionView *_airPlaySection;
@private
	SBCCButtonLikeSectionView *_airDropSection;
	MPAVRoutingController *_airPlayController;
	MPAVRoutingSheet *_airPlayModalSheet;
@protected
	MPAVRoutingViewController *_airPlayViewController;
	MPAudioVideoRoutingPopoverController *_airPlayPopoverController;
@private
	SFAirDropDiscoveryController *_airDropDiscoveryController;
	UIAlertController *_airDropAlertController;
@protected
	BOOL _isVisible;
@private
	BOOL _airPlayWasPreviouslyEnabled;
	BSTimer *_resetTimer;
	BSTimer *_airPlayTimer;
@protected
	BOOL _airPlayEnabled;
@private
	BOOL _airDropEnabled;
}
@property(assign, nonatomic) BOOL airDropEnabled;
@property(assign, nonatomic) BOOL airPlayEnabled;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
+ (id)defaultFont;
+ (id)defaultFontTight;
+ (Class)viewClass;
- (id)init;
- (void)_airDropTapped:(id)tapped;
- (void)_airPlayDoneButtonTapped:(id)tapped;
- (void)_airPlayTapped:(id)tapped;
- (void)_debugAirplaneStateDidChangeNotification:(id)_debugAirplaneState;
- (void)_debugWifiStateDidChangeNotification:(id)_debugWifiState;
- (void)_dismissAirplayControllerAnimated:(BOOL)animated;
- (void)_noteSectionEnabledStateDidChange;
- (void)_showAirPlayView:(id)view;
- (void)_updateAirDropControlAsEnabled:(BOOL)enabled;
- (void)_updateAirPlayControlAsEnabled:(BOOL)enabled;
- (void)_updateForAirDropStateChange;
- (void)_updateForAirPlayStateChange;
- (void)_updateLayoutForSizeCategoryChange;
- (void)_updateSubsectionVisibilityAnimated:(BOOL)animated;
- (CGSize)contentSizeForOrientation:(int)orientation;
- (void)controlCenterDidDismiss;
- (void)controlCenterWillPresent;
- (void)dealloc;
- (void)discoveryController:(id)controller alertControllerDidDismiss:(id)alertController;
- (void)discoveryControllerSettingsDidChange:(id)discoveryControllerSettings;
- (void)discoveryControllerVisibilityDidChange:(id)discoveryControllerVisibility;
- (BOOL)enabledForOrientation:(int)orientation;
- (void)popoverControllerDidDismissPopover:(id)popoverController;
- (void)routingControllerAvailableRoutesDidChange:(id)routingControllerAvailableRoutes;
- (id)sectionIdentifier;
- (id)view;
- (void)viewDidLoad;
@end

