/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBCommandTabSettings : XXUnknownSuperclass {
	BOOL _dimmingView;
	float _numberOfAppsLandscape;
	float _numberOfAppsPortrait;
	float _barHeight;
	float _barEdgeMarginLandscape;
	float _barEdgeMarginPortrait;
	float _iconMargin;
	float _selectionSquareSize;
}
@property(assign, nonatomic) float barEdgeMarginLandscape;
@property(assign, nonatomic) float barEdgeMarginPortrait;
@property(assign, nonatomic) float barHeight;
@property(assign, nonatomic) BOOL dimmingView;
@property(assign, nonatomic) float iconMargin;
@property(assign, nonatomic) float numberOfAppsLandscape;
@property(assign, nonatomic) float numberOfAppsPortrait;
@property(assign, nonatomic) float selectionSquareSize;
+ (id)settingsControllerModule;
- (void)setDefaultValues;
@end

