/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBControlCenterObserver <NSObject>
- (void)controlCenterDidDismiss;
- (void)controlCenterDidFinishTransition;
- (void)controlCenterWillBeginTransition;
@optional
- (void)controlCenterWillFinishTransitionOpen:(BOOL)controlCenter withDuration:(double)duration;
@required
- (void)controlCenterWillPresent;
@end

