/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBControlCenterKnockoutView : XXUnknownSuperclass <SBUIControlCenterControl> {
}
- (id)initWithFrame:(CGRect)frame;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (void)controlAppearanceDidChangeForState:(int)controlAppearance;
- (void)controlConfigurationDidChangeForState:(int)controlConfiguration;
- (void)dealloc;
@end

