/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBConferenceManager : XXUnknownSuperclass {
	BOOL _hasFaceTimeCapability;
	MGNotificationTokenStructRef _faceTimeCapabilityUpdateToken;
}
+ (void)initialize;
+ (id)sharedInstance;
- (id)init;
- (id)_faceTimeApp;
- (void)_faceTimeCapabilityChanged:(id)changed;
- (void)_faceTimeStateChanged:(id)changed;
- (void)_updateStatusBarForChat:(id)chat;
- (id)activeFaceTimeCall;
- (BOOL)activeFaceTimeCallExists;
- (BOOL)canStartFaceTime;
- (id)currentCallRemoteUserId;
- (id)currentCallStatusDisplayString;
- (id)currentFaceTimeCall;
- (void)dealloc;
- (void)endFaceTime;
- (BOOL)faceTimeInvitationExists;
- (BOOL)faceTimeIsAvailable;
- (BOOL)hasFaceTimeCapability;
- (BOOL)inFaceTime;
- (id)incomingFaceTimeCall;
- (void)invitedToIMAVChat:(id)imavchat;
- (void)updateStatusBarForChat:(id)chat;
@end

