/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBScaleIconZoomAnimator.h"


__attribute__((visibility("hidden")))
@interface SBCrossfadeIconZoomAnimator : SBScaleIconZoomAnimator {
	UIView *_crossfadeView;
	BOOL _performsTrueCrossfade;
	BOOL _masksCorners;
}
@property(assign, nonatomic) BOOL masksCorners;
@property(assign, nonatomic) BOOL performsTrueCrossfade;
@property(retain, nonatomic) SBCrossfadeZoomSettings *zoomSettings;
- (id)initWithFolderController:(id)folderController crossfadeView:(id)view icon:(id)icon;
- (void)_animateToZoomFraction:(float)zoomFraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
- (void)_assertCrossfadeViewSizeIfNecessary;
- (void)_cleanupZoom;
- (void)_delayedForRotation;
- (unsigned)_numberOfSignificantAnimations;
- (void)_prepareZoom;
- (void)_setZoomFraction:(float)fraction;
- (CGRect)_zoomedFrame;
- (CGPoint)_zoomedIconCenter;
- (void)dealloc;
@end

