/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBDarkeningImageView : XXUnknownSuperclass {
	UIImage *_baseImage;
	float _brightness;
}
@property(assign, nonatomic) float brightness;
- (id)initWithFrame:(CGRect)frame;
- (void)dealloc;
- (id)description;
- (void)setImage:(id)image;
- (void)setImage:(id)image brightness:(float)brightness;
@end

