/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDeviceLockView.h"

@class SBDeviceLockKeypad;

@interface SBDeviceLockViewWithKeypad : SBDeviceLockView {
	SBDeviceLockKeypad *_keypad;
}
- (id)initWithStyle:(int)style interfaceOrientation:(int)orientation;
- (void)dealloc;
- (void)deviceLockEntryFieldTextDidChange:(id)deviceLockEntryFieldText;
- (id)keypadView;
- (void)phonePad:(id)pad keyDown:(BOOL)down;
- (void)phonePad:(id)pad keyUp:(BOOL)up;
- (BOOL)playsKeyboardClicks;
- (id)protectedInitWithStyle:(int)style interfaceOrientation:(int)orientation;
- (void)setPasscode:(id)passcode;
- (void)setPlaysKeyboardClicks:(BOOL)clicks;
- (void)setShowsEmergencyCallButton:(BOOL)button;
- (BOOL)showsEmergencyCallButton;
@end

