/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDeviceLockDisableAssertion : XXUnknownSuperclass {
	NSString *_identifier;
	int _type;
}
- (id)initWithIdentifier:(id)identifier type:(int)type;
- (void)dealloc;
- (id)description;
- (int)type;
@end

