/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBDeviceLockPasscodeEntryAlert : SBAlert {
}
+ (id)sharedInstance;
- (id)alertDisplayViewWithSize:(CGSize)size;
- (void)deactivate;
- (int)statusBarMode;
@end

