/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBDeviceLockViewWithKeyboardWildcat : SBDeviceLockViewWithKeyboard {
}
- (void)_centerStatusView;
- (id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;
- (void)_layoutForCurrentOrientation;
- (void)hardwareReturnKeyPressed:(id)pressed;
- (void)returnKeyPressed:(id)pressed;
- (void)setInterfaceOrientation:(int)orientation;
- (void)setMinimized:(BOOL)minimized;
@end

