/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIWindow.h>
#import "SpringBoard-Structs.h"


@interface SBDimmingWindow : UIWindow {
}
+ (CGRect)constrainFrameToScreen:(CGRect)screen;
- (id)initWithContentRect:(CGRect)contentRect;
- (id)initWithDimmingImage:(id)dimmingImage;
- (BOOL)_disableGroupOpacity;
@end

