/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBLeafIcon.h"


__attribute__((visibility("hidden")))
@interface SBDownloadingIcon : SBLeafIcon {
	BOOL _wasUninstalledByUser;
	BOOL _isNewsstandDownload;
	SBApplicationPlaceholder *_appPlaceholder;
}
+ (id)leafIdentifierForApplicationPlaceholder:(id)applicationPlaceholder;
+ (id)leafIdentifierForApplicationPlaceholderBundleID:(id)applicationPlaceholderBundleID;
- (id)initWithApplicationPlaceholder:(id)applicationPlaceholder;
- (id)_darkenedIconImageForImage:(id)image;
- (void)_showAlertForError:(id)error;
- (id)appPlaceholder;
- (void)cancelDownload;
- (void)completeUninstall;
- (id)copyWithZone:(NSZone *)zone;
- (void)dealloc;
- (id)description;
- (id)gridCellImage;
- (id)homescreenIconImage;
- (BOOL)iconAppearsInNewsstand;
- (id)identifierForCorrespondingApplicationIcon;
- (BOOL)isNewsstandDownload;
- (BOOL)matchesApplicationIcon:(id)icon;
- (BOOL)matchesRepresentation:(id)representation;
- (id)realDisplayName;
- (void)reloadForStatusChange;
- (id)representation;
- (void)setApplicationPlaceholder:(id)placeholder;
- (void)setNewsstandDownload:(BOOL)download;
- (void)setUninstalledByUser:(BOOL)user;
- (id)uninstallAlertBody;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertTitle;
- (BOOL)uninstalledByUser;
@end

