/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIcon.h"
#import "SpringBoard-Structs.h"
#import "ISDownloadDelegate.h"

@class NSString, ISDownload, ISDownloadStatus, SBDownloadingProgressBar;

@interface SBDownloadingIcon : SBIcon <ISDownloadDelegate> {
	NSString *_displayID;
	NSString *_bundleID;
	ISDownload *_download;
	SBDownloadingProgressBar *_progressView;
	float _progress;
	BOOL _installing;
	BOOL _wasUninstalledByUser;
	ISDownloadStatus *_lastStatus;
}
+ (id)displayIdentifierForDownload:(id)download;
+ (id)displayIdentifierForDownloadUniqueID:(id)downloadUniqueID;
- (id)initWithDisplayIdentifier:(id)displayIdentifier;
- (id)initWithDownload:(id)download;
- (void)_reloadIcon;
- (void)_showAlertForError:(id)error;
- (BOOL)allowsCloseBox;
- (id)bundleID;
- (void)closeBoxClicked:(id)clicked;
- (void)completeUninstall;
- (void)dealloc;
- (id)description;
- (id)displayIdentifier;
- (id)displayName;
- (id)download;
- (void)download:(id)download encounteredError:(id)error;
- (void)download:(id)download loadedArtworkImage:(CGImageRef)image;
- (void)downloadStatusChanged:(id)changed;
- (id)icon;
- (void)launch;
- (id)modificationDate:(BOOL)date;
- (void)remove;
- (void)retry;
- (void)setBundleID:(id)anId;
- (void)setDisplayIdentifier:(id)identifier;
- (void)setDisplayedIcon:(id)icon;
- (void)setDownload:(id)download;
- (BOOL)shouldEllipsizeLabel;
- (BOOL)shouldKernLabel;
- (id)uninstallAlertBody;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertTitle;
- (void)updateDisplayName;
@end

