/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBFakeSUDescriptor : XXUnknownSuperclass {
}
- (id)documentation;
- (unsigned long long)downloadSize;
- (id)humanReadableUpdateName;
- (unsigned long long)installationSize;
- (BOOL)isDownloadable;
- (BOOL)isDownloadableOverCellular;
- (unsigned long long)preparationSize;
- (id)productBuildVersion;
- (id)productSystemName;
- (id)productVersion;
- (id)publisher;
- (int)updateType;
@end

