/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBFolderZoomSettings : SBScaleZoomSettings {
	SBAnimationSettings *_innerFolderFadeSettings;
}
@property(retain) SBAnimationSettings *innerFolderFadeSettings;
+ (id)settingsControllerModule;
- (void)setDefaultValues;
@end

