/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBFolderNotchView : XXUnknownSuperclass {
	XXStruct_9ihRqB _notchInfo;
	int _orientation;
}
+ (id)_imageForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;
+ (id)_keyComponentForNotchInfoRect:(CGRect)notchInfoRect;
+ (id)_keyForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;
+ (id)_squareImageForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;
+ (id)notchForNotchInfo:(XXStruct_9ihRqB)notchInfo orientation:(int)orientation;
- (id)initWithFrame:(CGRect)frame notchInfo:(XXStruct_9ihRqB)info orientation:(int)orientation;
- (void)setNotchInfo:(XXStruct_9ihRqB)info orientation:(int)orientation;
@end

