/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>
#import "UITextFieldDelegate.h"

@class SBFolderTitleLabel, SBFolderTextField, SBFolderShadowView, SBFolderIconListView, SBFolder;

@interface SBFolderView : UIView <UITextFieldDelegate> {
	SBFolder *_folder;
	SBFolderTitleLabel *_label;
	SBFolderShadowView *_shadowView;
	SBFolderTextField *_textField;
	SBFolderIconListView *_iconListView;
	BOOL _isEditing;
	unsigned _rows;
	XXStruct_9ihRqB _notchInfo;
}
- (id)initWithRows:(unsigned)rows notchInfo:(XXStruct_9ihRqB)info;
- (void)dealloc;
- (id)editTitleField;
- (void)enableShiftForFolderTextFieldAfterBeginEditing;
- (id)iconListView;
- (unsigned)rows;
- (void)setBackgroundAlpha:(float)alpha;
- (void)setFolder:(id)folder;
- (void)setFolderName:(id)name;
- (void)setIconListView:(id)view;
- (void)setIsEditing:(BOOL)editing animated:(BOOL)animated;
- (float)slideHeight;
- (BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
- (NSRange)textField:(id)field willChangeSelectionFromCharacterRange:(NSRange)characterRange toCharacterRange:(NSRange)characterRange3;
- (void)textFieldDidBeginEditing:(id)textField;
- (void)textFieldDidEndEditing:(id)textField;
- (BOOL)textFieldShouldClear:(id)textField;
- (BOOL)textFieldShouldReturn:(id)textField;
@end

