/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIconListView.h"
#import "SpringBoard-Structs.h"


@interface SBFolderIconListView : SBIconListView {
}
+ (unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
+ (unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;
- (float)bottomIconInset;
- (CGRect)nineIconRectForScrollPosition:(int)scrollPosition;
- (float)topIconInset;
@end

