/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBFolderIconListView : SBIconListView {
}
+ (int)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
+ (int)iconRowsForInterfaceOrientation:(int)interfaceOrientation;
- (float)bottomIconInset;
- (CGRect)nineIconRectForScrollPosition:(int)scrollPosition;
- (float)topIconInset;
@end

