/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBScaleIconZoomAnimator.h"

@class SBFolderIcon, _SBInnerFolderIconZoomAnimator, SBFolderController, SBFloatyFolderView, SBFolderZoomSettings, SBFolderIconView;

__attribute__((visibility("hidden")))
@interface SBFolderIconZoomAnimator : SBScaleIconZoomAnimator {
	SBFolderController *_innerFolderController;
	SBFloatyFolderView *_innerFolderView;
	_SBInnerFolderIconZoomAnimator *_innerZoomAnimator;
}
@property(retain, nonatomic) SBFolderZoomSettings *settings;
@property(readonly, assign, nonatomic) SBFolderIcon *targetIcon;
@property(readonly, assign, nonatomic) SBFolderIconView *targetIconView;
- (id)initWithOuterController:(id)outerController innerController:(id)controller folderIcon:(id)icon;
- (void)_animateToFraction:(float)fraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
- (void)_cleanupAnimation;
- (unsigned)_numberOfSignificantAnimations;
- (void)_prepareAnimation;
- (void)_setAnimationFraction:(float)fraction;
- (CGRect)_zoomedFrame;
- (void)dealloc;
@end

