/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBZoomView.h"


__attribute__((visibility("hidden")))
@interface SBFullscreenZoomView : SBZoomView {
	BOOL _hasImage;
	BOOL _hasFullSizedImage;
	int _corners;
	NSMutableArray *_cornerViews;
}
- (id)initWithImage:(id)image;
- (id)initWithSnapshotFrame:(CGRect)snapshotFrame image:(id)image originalImageOrientation:(int)orientation currentImageOrientation:(int)orientation4 interfaceOrientation:(int)orientation5 doubleHeightStatusBar:(BOOL)bar preventSplit:(BOOL)split chrome:(id)chrome chromeStatusBarHidden:(BOOL)hidden needsZoomFilter:(BOOL)filter asyncDecodeImage:(BOOL)image11;
- (id)initWithSnapshotFrame:(CGRect)snapshotFrame ioSurface:(void *)surface snapshotTransform:(CGAffineTransform)transform;
- (id)initWithView:(id)view;
- (id)_initWithFrame:(CGRect)frame;
- (void)dealloc;
- (void)setRoundedCorners:(int)corners withCornersFrame:(CGRect)cornersFrame;
@end

