/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBFWallpaperViewInternalObserver <NSObject>
- (void)wallpaperView:(id)view didChangeZoomFactor:(float)factor;
- (void)wallpaperViewDidChangeWantsRasterization:(id)wallpaperView;
- (void)wallpaperViewDidInvalidateBlurs:(id)wallpaperView;
- (void)wallpaperViewDidInvalidateGeometry:(id)wallpaperView;
@end

