/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBGestureMotionParams : XXUnknownSuperclass {
	float _animationDistance;
	float _commitDistance;
	float _accelerationThreshold;
	float _accelerationPower;
	int _requiredDirectionality;
	float _defaultHandSize;
	float _handSizeCompensationPower;
	float _sigmoidInflection_mmps;
	float _sigmoidAmplitude;
	float _sigmoidSharpness;
}
@property(assign, nonatomic) float accelerationPower;
@property(assign, nonatomic) float accelerationThreshold;
@property(assign, nonatomic) float animationDistance;
@property(assign, nonatomic) float commitDistance;
@property(assign, nonatomic) float defaultHandSize;
@property(assign, nonatomic) float handSizeCompensationPower;
@property(assign, nonatomic) int requiredDirectionality;
- (void)clear;
- (float)computeHandSizeCompensationGain:(float)gain;
- (float)computeNonlinearSpeedGain:(float)gain;
@end

