/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBGestureViewCacheNode : XXUnknownSuperclass {
	UIView *m_view;
	int m_viewType;
	NSString *m_contextHostViewRequester;
	int m_orientation;
	NSString *m_bundleIdentifier;
	BOOL m_includesStatusBar;
}
@property(copy, nonatomic) NSString *bundleIdentifier;
@property(copy, nonatomic) NSString *contextHostViewRequester;
@property(assign, nonatomic) BOOL includesStatusBar;
@property(assign, nonatomic) int orientation;
@property(retain, nonatomic) UIView *view;
@property(assign, nonatomic) int viewType;
+ (id)node;
- (void)dealloc;
@end

