/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBHostRequesterInfo : XXUnknownSuperclass {
	UIView *_wrapperView;
	NSMutableSet *_hiddenContexts;
	NSDictionary *_realContextHostViewChangedProperties;
	NSDictionary *_realContextHostViewOriginalProperties;
}
@property(readonly, assign, nonatomic) NSMutableSet *hiddenContexts;
@property(retain, nonatomic) NSDictionary *realContextHostViewChangedProperties;
@property(retain, nonatomic) NSDictionary *realContextHostViewOriginalProperties;
@property(readonly, assign, nonatomic) UIView *wrapperView;
- (id)init;
- (void)dealloc;
@end

