/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface SBIconModel : NSObject {
	NSDictionary *_previousIconState;
	NSMutableArray *_iconLists;
	SBButtonBar *_buttonBar;
	NSMutableDictionary *_allIcons;
	NSSet *_hiddenIconTags;
	NSSet *_visibleIconTags;
	SBImageCache *_iconImageCache;
	SBImageCache *_smallIconImageCache;
}
+ (int)maxIconListCount;
+ (id)sharedInstance;
- (id)init;
- (id)_addBookmarkIconForWebClip:(id)webClip;
- (void)_addIconForApplication:(id)application;
- (void)_addNewIconToDesignatedLocation:(id)designatedLocation animate:(BOOL)animate scrollToList:(BOOL)list saveIconState:(BOOL)state;
- (void)_cacheImagesForIcon:(id)icon small:(BOOL)small;
- (void)_completedUninstall:(id)uninstall;
- (BOOL)_iconListsAreDirty;
- (id)_iconState;
- (void)_purgeAndSaveCachedImages;
- (void)_purgeAndSaveCachedImages:(id)images;
- (void)_replaceAppIconWithDownloadingIcon:(id)downloadingIcon sourceList:(id)list;
- (void)_replaceAppIconsWithDownloadingIcons;
- (void)_writeIconState;
- (id)addBookmarkIconForWebClip:(id)webClip;
- (id)addDownloadingIconForDisplayIdentifier:(id)displayIdentifier;
- (id)addDownloadingIconForDownload:(id)download;
- (id)addEmptyIconList;
- (void)addIconForApplication:(id)application;
- (void)addNewIconToDesignatedLocation:(id)designatedLocation animate:(BOOL)animate scrollToList:(BOOL)list saveIconState:(BOOL)state;
- (id)allIcons;
- (id)buttonBar;
- (void)cacheImagesForIcon:(id)icon;
- (void)clearPreviousIconState;
- (void)compactIconLists;
- (void)createIconLists;
- (void)dealloc;
- (void)deleteIconState;
- (id)firstAvailableIconListX:(int *)x Y:(int *)y;
- (id)getCachedImagedForIcon:(id)icon smallIcon:(BOOL)icon2;
- (id)iconForDisplayIdentifier:(id)displayIdentifier;
- (id)iconListContainingIcon:(id)icon;
- (id)iconListContainingIconWithDisplayIdentifier:(id)displayIdentifier;
- (id)iconLists;
- (BOOL)iconPositionInPlatformState:(id)platformState X:(int *)x Y:(int *)y inIconListNumber:(int *)iconListNumber;
- (id)iconState;
- (int)indexOfIconList:(id)iconList;
- (BOOL)isIconVisible:(id)visible;
- (void)loadAllIcons;
- (void)localeChanged;
- (void)noteIconStateChangedExternally;
- (void)relayout;
- (void)reloadIconImage:(id)image;
- (void)reloadIconImageForDisplayIdentifier:(id)displayIdentifier;
- (void)removeAppForDownloadingIcon:(id)downloadingIcon;
- (void)removeEmptyIconList:(id)list;
- (void)replaceDownloadingDisplayIdentifiers:(id)identifiers withDisplayIdentifiers:(id)displayIdentifiers;
- (void)saveIconState;
- (void)setVisibilityOfIconsWithVisibleTags:(id)visibleTags hiddenTags:(id)tags;
- (void)uninstallApplicationIcon:(id)icon;
- (void)uninstallBookmarkIcon:(id)icon;
- (id)visibleIconIdentifiers;
@end

