/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"

@class NSString;

@interface SBIconLabelProperties : XXUnknownSuperclass <NSCopying> {
	NSString *_text;
	NSString *_labelClassString;
	BOOL _ellipsize;
	BOOL _inDock;
	BOOL _onWallpaper;
	CGSize _size;
	BOOL _appearsInDock;
	BOOL _appearsOnWallpaper;
}
@property(assign, nonatomic) BOOL appearsInDock;
@property(assign, nonatomic) BOOL appearsOnWallpaper;
@property(assign, nonatomic) BOOL ellipsize;
@property(assign, nonatomic) Class labelClass;
@property(assign, nonatomic) CGSize size;
@property(retain, nonatomic) NSString *text;
- (id)copyWithZone:(NSZone *)zone;
- (void)dealloc;
- (id)description;
- (unsigned)hash;
- (BOOL)isEqual:(id)equal;
- (id)labelClassString;
@end

