/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBIconModel : XXUnknownSuperclass {
	NSDictionary *_lastKnownUserGeneratedIconState;
	NSSet *_lastKnownUserGeneratedIconStateFlattened;
	NSMutableDictionary *_leafIconsByIdentifier;
	NSSet *_hiddenIconTags;
	NSSet *_visibleIconTags;
	BOOL _tagsHaveBeenSet;
	NSMutableSet *_downloadedIconIDs;
	SBRootFolder *_rootFolder;
	SBNewsstandIcon *_newsstandIcon;
	BOOL _needsRelayout;
	BOOL _allowReadingCachedStateFromDisk;
}
+ (id)_migrateLeafIdentifierIfNecessary:(id)necessary;
+ (id)_modernIconCellForCell:(id)cell;
+ (id)_modernIconListForList:(id)list;
+ (id)_modernIconListsForLists:(id)lists;
+ (id)modernIconStateForState:(id)state;
+ (id)sharedInstance;
- (id)init;
- (void)_addNewIconToDesignatedLocation:(id)designatedLocation;
- (void)_addNodeToRootLists:(id)rootLists node:(id)node createListIfNecessary:(BOOL)necessary;
- (id)_applicationIcons;
- (id)_cachedIconStatePath;
- (void)_createIconLists;
- (id)_deepCopyIconState:(id)state;
- (id)_deepCopyListForIconState:(id)iconState;
- (void)_flattenIconListState:(id)state intoArray:(id)array;
- (id)_flattenIconState:(id)state;
- (id)_iTunesDictionaryForDownloadingIcon:(id)downloadingIcon;
- (id)_iTunesDictionaryForLeafIcon:(id)leafIcon;
- (id)_iTunesDictionaryForLeafIdentifier:(id)leafIdentifier;
- (id)_iTunesIconCellForCell:(id)cell preApex:(BOOL)apex forPending:(BOOL)pending;
- (id)_iTunesIconListForList:(id)list preApex:(BOOL)apex forPending:(BOOL)pending;
- (id)_iTunesIconListsForLists:(id)lists preApex:(BOOL)apex forPending:(BOOL)pending;
- (id)_iconState:(BOOL)state;
- (id)_indexPathForFirstFreeNewsstandSlot;
- (id)_indexPathForIdentifier:(id)identifier inListRepresentation:(id)listRepresentation;
- (id)_indexPathForIdentifier:(id)identifier inListsRepresentation:(id)listsRepresentation;
- (id)_newsstandIconIdentifiersFromIconState:(id)iconState;
- (void)_replaceAppIconsWithDownloadingIcons;
- (void)_replaceAppIconsWithDownloadingIcons:(id)downloadingIcons;
- (id)_trimList:(id)list toMaxSize:(int)maxSize;
- (void)_writeCachedIconState;
- (void)_writeCurrentIconStateWithNotification:(BOOL)notification;
- (BOOL)_writeIconState:(id)state toPath:(id)path;
- (BOOL)_writeIconState:(id)state toPath:(id)path withFormat:(unsigned)format;
- (id)addBookmarkIconForWebClip:(id)webClip;
- (id)addDownloadingIconForDownload:(id)download;
- (id)addDownloadingIconForIdentifier:(id)identifier;
- (void)addIcon:(id)icon;
- (void)addIconForApplication:(id)application;
- (void)addNewsstandIcon;
- (id)applicationIconForDisplayIdentifier:(id)displayIdentifier;
- (void)clearCachedUserGeneratedIconState;
- (void)clearCachedUserGeneratedIconStateIfPossible;
- (void)dealloc;
- (void)deleteIconState;
- (id)downloadedIconIDs;
- (id)downloadingIconForIdentifier:(id)identifier;
- (id)exportFlattenedState:(BOOL)state;
- (id)exportPendingState:(BOOL)state;
- (id)exportState:(BOOL)state;
- (id)firstPageLeafIdentifiers;
- (id)forecastedLayoutForIconState:(id)iconState;
- (BOOL)hasCachedUserGeneratedIconState;
- (id)iconState;
- (id)iconStatePath;
- (BOOL)importState:(id)state;
- (id)indexPathForIconInPlatformState:(id)platformState;
- (id)indexPathForNewIcon:(id)newIcon isDesignatedLocation:(BOOL *)location replaceExistingIconAtIndexPath:(id *)indexPath;
- (BOOL)isIconVisible:(id)visible;
- (id)leafIconForIdentifier:(id)identifier;
- (id)leafIcons;
- (void)loadAllIcons;
- (void)localeChanged;
- (id)newsstandFolder;
- (id)newsstandFolderFromIconState:(id)iconState;
- (id)newsstandIcon;
- (void)noteDownloadCompletedForIconID:(id)iconID;
- (void)noteDownloadsEnded;
- (void)noteFolderStoppedAnimating;
- (void)noteIconStateChangedExternally;
- (void)relayout;
- (void)removeApplicationIconForDownloadingIcon:(id)downloadingIcon;
- (void)removeDownloadedIconID:(id)anId;
- (void)removeIcon:(id)icon;
- (void)removeIconForIdentifier:(id)identifier;
- (id)rootFolder;
- (void)saveIconState;
- (void)setVisibilityOfIconsWithVisibleTags:(id)visibleTags hiddenTags:(id)tags;
- (void)uninstallApplicationIcon:(id)icon;
- (void)uninstallBookmarkIcon:(id)icon;
- (id)visibleIconIdentifiers;
@end

