/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBIconLabel : UIControl {
	NSString *_label;
	unsigned _drawMoreLegibly : 1;
	unsigned _inDock : 1;
	unsigned _ellipsesText : 1;
	unsigned _kerningAllowed : 1;
	unsigned _textMightOverlap : 1;
}
- (id)initWithSize:(CGSize)size label:(id)label;
- (void)dealloc;
- (void)drawRect:(CGRect)rect;
- (void)setEllipsesText:(BOOL)text;
- (void)setInDock:(BOOL)dock;
- (void)setKerningAllowed:(BOOL)allowed;
@end

