/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBIconLabelImageCache : XXUnknownSuperclass {
	NSMutableDictionary *_cache;
}
+ (id)sharedInstance;
- (id)init;
- (void)cacheNewLabelImage:(id)image;
- (void)checkinLabelImage:(id)image;
- (id)checkoutLabelImageForPropertiesIfExists:(id)propertiesIfExists;
- (void)dealloc;
@end

