/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBIconPageIndicatorImageSetCache : XXUnknownSuperclass {
	_UILegibilitySettings *_legibilitySettings;
	SBIconPageIndicatorImageSetResult *_indicatorImageSetResults;
	SBIconPageIndicatorImageSetResult *_searchImageSetResults;
}
+ (id)homescreenPageIndicatorImageSetCache;
- (id)_emptyPageIndicatorSet;
- (void)dealloc;
- (id)pageIndicatorImageSetForLegibilitySettings:(id)legibilitySettings;
- (id)searchIndicatorImageSetForLegibilitySettings:(id)legibilitySettings;
- (void)setLegibilitySettings:(id)settings;
@end

