/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class SBRootFolder, NSSet, NSMutableSet, NSDictionary, NSMutableDictionary;

@interface SBIconModel : NSObject {
	NSDictionary *_lastKnownUserGeneratedIconState;
	NSMutableDictionary *_leafIconsByIdentifier;
	NSSet *_hiddenIconTags;
	NSSet *_visibleIconTags;
	NSMutableSet *_downloadedIconIDs;
	SBRootFolder *_rootFolder;
	BOOL _needsRelayout;
}
+ (id)_modernIconCellForCell:(id)cell;
+ (id)_modernIconListForList:(id)list;
+ (id)_modernIconListsForLists:(id)lists;
+ (id)modernIconStateForState:(id)state;
+ (id)sharedInstance;
- (id)init;
- (void)_addNewIconToDesignatedLocation:(id)designatedLocation;
- (id)_iTunesDictionaryForLeafIcon:(id)leafIcon;
- (id)_iTunesIconCellForCell:(id)cell preApex:(BOOL)apex;
- (id)_iTunesIconListForList:(id)list preApex:(BOOL)apex;
- (id)_iTunesIconListsForLists:(id)lists preApex:(BOOL)apex;
- (id)_iconState;
- (id)_indexPathForIdentifier:(id)identifier inListRepresentation:(id)listRepresentation;
- (id)_indexPathForIdentifier:(id)identifier inListsRepresentation:(id)listsRepresentation;
- (void)_replaceAppIconWithDownloadingIcon:(id)downloadingIcon;
- (void)_replaceAppIconsWithDownloadingIcons;
- (void)_writeIconStateWithNotification:(BOOL)notification;
- (id)addBookmarkIconForWebClip:(id)webClip;
- (id)addDownloadingIconForDownload:(id)download;
- (id)addDownloadingIconForIdentifier:(id)identifier;
- (void)addIcon:(id)icon;
- (void)addIconForApplication:(id)application;
- (id)applicationIconForDisplayIdentifier:(id)displayIdentifier;
- (id)applicationIcons;
- (void)clearCachedUserGeneratedIconState;
- (void)createIconLists;
- (void)dealloc;
- (void)deleteIconState;
- (id)designatedIndexPathForNewIcon:(id)newIcon replaceExistingIcon:(BOOL *)icon;
- (id)downloadedIconIDs;
- (id)exportState:(BOOL)state;
- (BOOL)hasCachedUserGeneratedIconState;
- (id)iconState;
- (id)iconStatePath;
- (BOOL)importState:(id)state;
- (id)indexPathForIconInPlatformState:(id)platformState;
- (BOOL)isIconVisible:(id)visible;
- (id)leafIconForIdentifier:(id)identifier;
- (id)leafIcons;
- (void)loadAllIcons;
- (void)localeChanged;
- (void)noteDownloadsCompletedForIconIDs:(id)iconIDs;
- (void)noteDownloadsEnded;
- (void)noteFolderStoppedAnimating;
- (void)noteIconStateChangedExternally;
- (void)relayout;
- (void)removeApplicationIconForDownloadingIcon:(id)downloadingIcon;
- (void)removeDownloadedIconID:(id)anId;
- (void)removeIcon:(id)icon;
- (void)removeIconForIdentifier:(id)identifier;
- (void)replaceDownloadingIconIdentifiers:(id)identifiers withAppIconIdentifiers:(id)appIconIdentifiers;
- (id)rootFolder;
- (void)saveIconState;
- (void)setVisibilityOfIconsWithVisibleTags:(id)visibleTags hiddenTags:(id)tags;
- (void)uninstallApplicationIcon:(id)icon;
- (void)uninstallBookmarkIcon:(id)icon;
- (void)uninstallLeafIcon:(id)icon;
- (id)visibleIconIdentifiers;
@end

