/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIControl.h>


@interface SBIcon : UIControl {
	UIImage *_topRimmedIcon;
	UIImageView *_image;
	UIImageView *_reflection;
	SBIconBadge *_badge;
	SBIconLabel *_label;
	UIPushButton *_closeBox;
	unsigned _drawsLabel : 1;
	unsigned _isHidden : 1;
	unsigned _isRevealable : 1;
	unsigned _inDock : 1;
	unsigned _isGrabbed : 1;
	unsigned _isGrabbing : 1;
	unsigned _isJittering : 1;
	unsigned _allowJitter : 1;
	unsigned _mouseDownInIcon : 1;
	int _keyFrameIndex;
	CGPoint _unjitterPoint;
	CGPoint _grabPoint;
	NSTimer *_grabTimer;
}
+ (id)_jitterPositionAnimation;
+ (id)_jitterTransformAnimation;
+ (CGSize)defaultIconSize;
- (id)initWithDefaultSize;
- (id)_automationID;
- (BOOL)allowJitter;
- (BOOL)allowsCloseBox;
- (id)badge;
- (void)cancelGrabTimer;
- (BOOL)cancelMouseTracking;
- (void)closeBoxClicked:(id)clicked;
- (void)completeUninstall;
- (id)darkenedIcon:(id)icon alpha:(float)alpha;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayIdentifier;
- (id)displayName;
- (float)grabDurationForEvent:(GSEventRef)event;
- (void)grabTimerFired;
- (void)hideCloseBoxAnimationDidStop:(id)hideCloseBoxAnimation didFinish:(id)finish closeBox:(id)box;
- (id)highlightedIcon;
- (id)icon;
- (BOOL)ignoresMouseEvents;
- (BOOL)isHidden;
- (BOOL)isRevealable;
- (BOOL)isShowingCloseBox;
- (void)launch;
- (BOOL)launchEnabled;
- (void)layout;
- (void)mouseCancelInIcon:(id)icon;
- (void)mouseDown:(GSEventRef)down;
- (void)mouseDragged:(GSEventRef)dragged;
- (void)mouseUp:(GSEventRef)up;
- (BOOL)pointInside:(CGPoint)inside forEvent:(GSEventRef)event;
- (BOOL)pointMostlyInside:(CGPoint)inside forEvent:(GSEventRef)event;
- (id)reflectedIcon:(BOOL)icon;
- (void)resetIconImage;
- (void)setAllowJitter:(BOOL)jitter;
- (void)setBadge:(id)badge;
- (void)setDisplayedIcon:(id)icon;
- (void)setDrawsLabel:(BOOL)label;
- (void)setHighlighted:(BOOL)highlighted;
- (void)setIconPosition:(CGPoint)position;
- (void)setInDock:(BOOL)dock;
- (void)setIsGrabbed:(BOOL)grabbed;
- (void)setIsHidden:(BOOL)hidden animate:(BOOL)animate;
- (void)setIsRevealable:(BOOL)revealable;
- (void)setIsShowingCloseBox:(BOOL)box;
- (void)setOrigin:(CGPoint)origin;
- (BOOL)shouldEllipsizeLabel;
- (BOOL)shouldListInCapabilities;
- (BOOL)shouldTrack;
- (void)showIconAnimationDidStop:(id)showIconAnimation didFinish:(id)finish icon:(id)icon;
- (void)startJitteringAnimation;
- (void)stopJitteringAnimation;
- (id)tags;
- (id)topRimmedIcon;
- (id)uninstallAlertBody;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertTitle;
- (void)unjitter;
- (void)updateLabelKerning;
- (void)updateLabelOrigin;
@end

