/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIconBadge.h"

@class UIImageView;

@interface SBIconImageBadge : SBIconBadge {
	UIImageView *_badgeImageView;
}
- (id)initWithImage:(id)image;
- (void)dealloc;
@end

