/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBIconFadeAnimator : SBIconAnimator {
	UIView *_crossfadeView;
	BOOL _addedToWindow;
}
- (id)initWithFolderController:(id)folderController crossfadeView:(id)view;
- (void)_animateToFraction:(float)fraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
- (void)_applyAlphaForFraction:(float)fraction;
- (void)_cleanupAnimation;
- (unsigned)_numberOfSignificantAnimations;
- (void)_prepareAnimation;
- (void)_setAnimationFraction:(float)fraction;
- (void)dealloc;
@end

