/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "SpringBoard-Structs.h"


@interface SBIconController : NSObject {
	SBIconModel *_iconModel;
	UIView *_contentView;
	UIScroller *_scroller;
	SBTouchPageIndicator *_pageIndicator;
	int _currentIconListIndex;
	TPLCDTextView *_idleText;
	SBApplicationIcon *_pendingIcon;
	SBIcon *_lastClickedIcon;
	double _lastClickedTime;
	SBIcon *_grabbedIcon;
	SBIconList *_grabbedIconList;
	int _grabbedX;
	int _grabbedY;
	SBIcon *_swappedIcon;
	SBIconList *_swappedIconList;
	int _swappedX;
	int _swappedY;
	SBIconList *_destinationIconList;
	int _destinationX;
	int _destinationY;
	NSTimer *_scrollPageTimer;
	unsigned _didScroll : 1;
	unsigned _isScrolling : 1;
	unsigned _isEditing : 1;
	unsigned _compacted : 1;
	unsigned _willSwap : 1;
	unsigned _animatingToNewState : 1;
	unsigned _animateToNewStateAfterDelay : 1;
	SBIcon *_iconToInstall;
	CGPoint _lastDragLoc;
	SBReorderInfoAlert *_reorderInfoAlert;
	SBCarrierDebuggingAlert *_carrierDebuggingAlert;
}
+ (id)sharedInstance;
- (id)init;
- (void)_addEmptyListIfNecessary;
- (void)_jitterOptionsChanged;
- (id)addIcon:(id)icon toIconList:(id)iconList x:(int)x y:(int)y animate:(BOOL)animate moveNow:(BOOL)now scrollToList:(BOOL)list;
- (void)animateToNewState:(float)newState domino:(BOOL)domino;
- (void)appendIconList:(id)list;
- (void)attemptPendingLaunch;
- (void)cancelScrollTimer;
- (void)clickedIcon:(id)icon;
- (void)compactIconsInIconLists:(BOOL)iconLists limitToIconList:(id)iconList;
- (id)contentView;
- (id)currentIconList;
- (void)dealloc;
- (id)destinationIconList;
- (void)doubleClickedIcon:(id)icon;
- (void)finishInstallingIcon;
- (id)grabbedIcon;
- (BOOL)hasIdleModeText;
- (BOOL)hasLaunchPending;
- (id)iconAnimationView;
- (id)iconToInstall;
- (float)idleModeTextHeight;
- (void)idleTextDidAnimate:(id)idleText finished:(id)finished toText:(id)text;
- (void)incrementReorderCount;
- (id)insertIcon:(id)icon intoIconList:(id)list X:(int)x Y:(int)y moveNow:(BOOL)now duration:(float)duration;
- (BOOL)isEditing;
- (void)jitterOptionsChanged;
- (void)launchIcon:(id)icon;
- (void)lcdTextViewCompletedScroll:(id)scroll;
- (int)lowestVisibleIconListIndex;
- (void)moveAnimation:(id)animation didFinish:(id)finish movePlan:(id)plan;
- (void)moveIcon:(id)icon fromIconList:(id)iconList toX:(int)x Y:(int)y toIconList:(id)iconList5;
- (void)moveIconFromWindow:(id)window toIconList:(id)iconList;
- (void)moveIconToWindow:(id)window;
- (void)noteDownloadStateChanged;
- (void)noteGrabbedIconLocationChangedWithEvent:(GSEventRef)event;
- (void)noteNumberOfIconListsChanged;
- (void)noteViewCovered;
- (void)pendLaunchOfIcon:(id)icon;
- (void)relayoutIcons;
- (void)removeAccessory:(id)accessory;
- (void)removeEmptyIconList:(id)list animate:(BOOL)animate;
- (void)removeIcon:(id)icon animate:(BOOL)animate;
- (int)reorderCount;
- (void)revealIconForDisplayIdentifier:(id)displayIdentifier;
- (void)scatter:(BOOL)scatter;
- (void)scrollLeft;
- (void)scrollRight;
- (void)scrollToIconDestination;
- (void)scrollToIconListAtIndex:(int)index animate:(BOOL)animate;
- (void)scrollToIconListContainingIcon:(id)iconListContainingIcon animate:(BOOL)animate;
- (void)scrollerDidEndAnimatedScrolling:(id)scroller;
- (void)scrollerDidEndDragging:(id)scroller willSmoothScroll:(BOOL)scroll;
- (void)scrollerDidEndSmoothScrolling:(id)scroller;
- (void)scrollerDidScroll:(id)scroller;
- (void)scrollerWillStartSmoothScrolling:(id)scroller;
- (void)setGrabbedIcon:(id)icon;
- (void)setIconToInstall:(id)install;
- (void)setIdleModeText:(id)text;
- (void)setIsEditing:(BOOL)editing;
- (void)showAccessory:(id)accessory;
- (void)showCarrierDebuggingAlertIfNeeded;
- (void)showInfoAlertIfNeeded;
- (void)startDraggingIcon:(id)icon fromIconList:(id)iconList;
- (void)startJitteringCurrentIconLists;
- (void)stopJitteringCurrentIconLists;
- (void)touchPageIndicator:(id)indicator didRecieveTouchInDirection:(int)direction;
- (void)ungrabAnimation:(id)animation didFinish:(id)finish grabbedIcon:(id)icon;
- (void)uninstallIcon:(id)icon;
- (void)uninstallIconDidAnimate:(id)uninstallIcon finished:(id)finished icon:(id)icon;
- (void)unscatter:(BOOL)unscatter startTime:(double)time;
- (void)updateContentSizeAndPageCount;
- (void)updateCurrentIconListIndexUpdatingPageIndicator:(BOOL)indicator;
- (void)updateNumberOfRowsWithDuration:(float)duration;
@end

