/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBInterfaceItemInfo : XXUnknownSuperclass {
	id _representedObject;
	UIImage *_icon;
	UIImage *_settingsIcon;
	NSString *_displayName;
	NSString *_settingsDisplayName;
}
@property(copy, nonatomic) NSString *displayName;
@property(retain, nonatomic) UIImage *icon;
@property(readonly, assign, nonatomic) NSString *identifier;
@property(readonly, retain, nonatomic) id representedObject;
@property(copy, nonatomic) NSString *settingsDisplayName;
@property(retain, nonatomic) UIImage *settingsIcon;
+ (id)infoWithRepresentedObject:(id)representedObject;
- (id)initWithRepresentedObject:(id)representedObject;
- (int)compare:(id)compare;
- (void)dealloc;
- (id)description;
- (unsigned)hash;
- (float)heightForReusableViewForNotificationCenterTableViewController:(id)notificationCenterTableViewController layoutMode:(int)mode sectionLocation:(int)location;
- (void)invalidateCachedLayoutData;
- (BOOL)isEqual:(id)equal;
- (void)populateReusableView:(id)view;
- (Class)reusableViewClass;
- (id)reusableViewIdentifier;
@end

