/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBItemInfoLayoutCache : XXUnknownSuperclass {
	float _cachedViewHeight;
	CGSize _referenceSize;
	int _layoutMode;
}
- (BOOL)_isLayoutValidWithReferenceSize:(CGSize)referenceSize layoutMode:(int)mode;
- (void)invalidateCache;
- (float)viewHeightWithReferenceSize:(CGSize)referenceSize layoutMode:(int)mode generateBlock:(id)block;
@end

