/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBLayoutElement : XXUnknownSuperclass <SBLayoutElementDescriptor, SBWorkspaceEntityGenerating> {
	NSString *_identifier;
	int _role;
	id _entityGenerator;
	unsigned _supportedLayoutRoles;
	unsigned _layoutAttributes;
	Class _viewControllerClass;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(copy, nonatomic) id entityGenerator;
@property(readonly, assign) unsigned hash;
@property(readonly, copy, nonatomic) NSString *identifier;
@property(readonly, assign, nonatomic) unsigned layoutAttributes;
@property(readonly, copy, nonatomic) NSString *layoutIdentifier;
@property(readonly, assign, nonatomic) int layoutRole;
@property(readonly, assign, nonatomic) int role;
@property(readonly, assign) Class superclass;
@property(readonly, assign, nonatomic) unsigned supportedLayoutRoles;
@property(readonly, assign, nonatomic) Class viewControllerClass;
+ (id)elementWithDescriptor:(id)descriptor role:(int)role;
- (id)initWithIdentifier:(id)identifier role:(int)role supportedRoles:(unsigned)roles attributes:(unsigned)attributes viewControllerClass:(Class)aClass entityGenerator:(id)generator;
- (void)dealloc;
- (id)descriptionBuilderWithMultilinePrefix:(id)multilinePrefix;
- (id)descriptionWithMultilinePrefix:(id)multilinePrefix;
- (BOOL)hasLayoutAttributes:(unsigned)attributes;
- (BOOL)hasSameIdentityAsElement:(id)element;
- (BOOL)isEqual:(id)equal;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (BOOL)supportsLayoutRole:(int)role;
- (id)workspaceEntity;
@end

