/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBLinenNotchView : UIImageView {
}
+ (id)_imageForNotchInfo:(XXStruct_9ihRqB)notchInfo;
+ (id)_keyForNotchInfo:(XXStruct_9ihRqB)notchInfo;
+ (id)notchForNotchInfo:(XXStruct_9ihRqB)notchInfo;
- (id)initWithFrame:(CGRect)frame notchInfo:(XXStruct_9ihRqB)info;
- (void)setNotchInfo:(XXStruct_9ihRqB)info;
@end

