/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBLockScreenDisableAssertion : XXUnknownSuperclass {
	NSString *_identifier;
	SBPasscodeLockDisableAssertion *_disableLockAssertion;
}
+ (void)initialize;
- (id)initWithIdentifier:(id)identifier;
- (void)dealloc;
- (id)description;
@end

