/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"


@interface SBLowPowerAlertItem : SBAlertItem {
	unsigned _talkLevel;
}
+ (BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned)batteryLevel;
+ (unsigned)_thresholdForLevel:(unsigned)level;
+ (void)saveLowBatteryLogWithCapacity:(int)capacity;
+ (void)setBatteryLevel:(unsigned)level;
+ (id)systemVersionDescription;
- (id)initWithLevel:(unsigned)level;
- (void)alertSheet:(id)sheet buttonClicked:(int)clicked;
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)shouldShowInLockScreen;
- (BOOL)undimsScreen;
- (void)willPresentAlertSheet:(id)sheet;
@end

