/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBLockScreenPluginTransition : XXUnknownSuperclass {
	SBAwayViewPluginController *_fromController;
	SBAwayViewPluginController *_toController;
	SBLockScreenViewController *_lockScreenViewController;
	SBLockOverlayContext *_fromOverlay;
	SBLockOverlayContext *_toOverlay;
}
@property(readonly, retain) SBAwayViewPluginController *fromController;
@property(readonly, retain) SBLockOverlayContext *fromOverlay;
@property(readonly, retain) SBLockScreenViewController *lockScreenViewController;
@property(readonly, retain) SBAwayViewPluginController *toController;
@property(readonly, retain) SBLockOverlayContext *toOverlay;
- (id)initWithContext:(id)context;
- (void)_addToView;
- (void)_removeFromView;
- (void)_removeViewFromHierarchy:(id)hierarchy;
- (void)beginTransition;
- (void)dealloc;
@end

