/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SBMappedImageCache : XXUnknownSuperclass {
	dispatch_queue_s *_queue;
	NSString *_path;
	NSMutableDictionary *_images;
}
+ (id)imageNamed:(id)named;
+ (id)persistentCache;
+ (id)sessionCache;
- (id)initWithPath:(id)path;
- (void)dealloc;
- (id)imageForKey:(id)key;
- (id)imageForKey:(id)key generateImageWithBlockIfNecessary:(id)blockIfNecessary;
- (void)removeAllObjects;
- (void)removeImageForKey:(id)key;
- (void)setImage:(id)image forKey:(id)key;
@end

