/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBMainDisplayLayoutContext <SBLayoutContext>
@property(readonly, assign, nonatomic) int externallyManagedSideAppPresentationStyle;
@property(readonly, assign, nonatomic) int externallyManagedSideAppWidth;
@property(readonly, assign, nonatomic) int sideAppPresentationStyle;
@property(readonly, assign, nonatomic) int sideAppWidth;
- (BOOL)includesStatusBarForLayoutRole:(int)layoutRole;
- (int)wallpaperMode;
- (int)wallpaperModeForLayoutRole:(int)layoutRole;
@end

