/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBMainAppSwitcherPageView : SBAppSwitcherPageView {
	int _orientation;
}
@property(assign, nonatomic) int orientation;
@property(retain, nonatomic) UIView<SBMainAppSwitcherPageContentView> *view;
+ (float)_horizontalEdgeBorderForOrientation:(int)orientation;
+ (CGSize)sizeForOrientation:(int)orientation;
- (CGPoint)_centerForSubviewLayout;
- (CGAffineTransform)_overlayRotationTransform;
- (CGAffineTransform)_scaleTransform;
- (CGRect)_viewFrame;
- (id)description;
- (void)setView:(id)view animated:(BOOL)animated;
- (CGSize)sizeThatFits:(CGSize)fits;
@end

