/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBMainWorkspaceEntity.h"


__attribute__((visibility("hidden")))
@interface SBMainWorkspaceSideSwitcherEntity : SBMainWorkspaceEntity {
}
- (id)init;
- (BOOL)_supportsDynamicResizing;
- (BOOL)_supportsLayoutRole:(int)role;
- (BOOL)_supportsPresentationAtAnySize;
- (BOOL)isSideSwitcherEntity;
- (Class)viewControllerClass;
@end

