/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UIWindow, SBApplication;

@interface SBMiniAlertController : NSObject {
	SBApplication *_displayShowingAnAlert;
	UIWindow *_dimmingWindow;
	unsigned _dontAskApps : 1;
	unsigned _reserved : 31;
}
+ (id)sharedInstance;
- (BOOL)canShowAlerts;
- (void)cancelHideDimmingWindow;
- (void)deactivateAlertItemsWithBundleIdentifier:(id)bundleIdentifier;
- (id)dimImageForKeyboard:(BOOL)keyboard;
- (void)displayDidDisableMiniAlerts:(id)display;
- (id)displayShowingAnAlert;
- (void)displayWillDismissMiniAlert:(id)display andShowAnother:(BOOL)another;
- (void)displayWillShowMiniAlert:(id)display;
- (void)finishedAnimatingDimWindowOut:(id)anOut didFinish:(id)finish;
- (void)hideApplicationMiniAlerts;
- (void)hideDimmingWindow;
- (void)hideDimmingWindowAfterDelay;
- (void)noteMiniAlertStateChanged;
- (void)setShouldAskApps:(BOOL)askApps;
- (void)showApplicationMiniAlertsIfNeeded;
- (void)showDimmingWindow;
@end

