/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBNetworkReselectionAlert : SBAlert {
}
+ (void)_serviceAvailabilityChanged:(id)changed;
+ (void)registerForAlerts;
+ (void)test;
@end

