/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBNewsstandIconRotationContainer : SBIconRotationContainer {
}
- (void)crossfadeWithDuration:(double)duration inIconList:(id)iconList;
- (void)setStartIcon:(id)icon endIcon:(id)icon2 inIconList:(id)iconList fromOrientation:(int)orientation toOrientation:(int)orientation5;
@end

