/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBNewsstandFolder : SBFolder {
}
- (id)init;
- (void)_setDisplayNameFromRepresentation:(id)representation;
- (BOOL)canAddIcon;
- (BOOL)canEditDisplayName;
- (BOOL)canRemoveIcons;
- (Class)controllerClass;
- (id)folderType;
- (id)icon;
- (BOOL)isNewsstandFolder;
- (Class)listModelClass;
- (Class)listViewClass;
- (id)nodeIdentifier;
- (void)setIsOpen:(BOOL)open;
- (BOOL)shouldRemoveWhenEmpty;
@end

