/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBNewsstandItemIconViewBase.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandItemIconView : SBNewsstandItemIconViewBase {
	UIView *_iconTransformView;
	UILabel *_indexLabel;
	unsigned _newsstandIndex;
}
+ (CGSize)_maxLabelSize;
+ (CGSize)defaultIconSize;
- (id)initWithDefaultSize;
- (id)initWithFrame:(CGRect)frame;
- (CGRect)_frameForAccessoryView;
- (void)applyIconImageTransform:(CATransform3D)transform duration:(float)duration delay:(float)delay;
- (id)createShadowImageView;
- (void)dealloc;
- (CGRect)defaultFrameForProgressBar;
- (BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
- (void)positionCloseBoxOfType:(int)type;
- (void)positionIconImageView;
- (void)positionLabel;
- (void)prepareForRecycling;
- (void)setIsGrabbed:(BOOL)grabbed;
- (void)setNewsstandIndex:(unsigned)index;
@end

