/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBNewsstandTilingImageView : XXUnknownSuperclass {
	UIImage *_tileImage;
}
@property(retain, nonatomic) UIImage *_tileImage;
@property(retain, nonatomic) UIImage *image;
- (id)initWithImage:(id)image;
- (void)dealloc;
@end

