/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class UIImage;

@interface SBNowPlayingReflectionView : UIView {
	UIImage *_image;
}
- (void)dealloc;
- (void)drawRect:(CGRect)rect;
- (void)setImage:(id)image;
@end

