/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIButton.h>


@interface SBNowPlayingAlertItemPushButton : UIButton {
	float _yOffset;
	float _xOffset;
}
+ (id)newButtonWithImage:(id)image;
- (CGRect)hitRect;
- (BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
- (void)setXOffset:(float)offset;
- (void)setYOffset:(float)offset;
@end

