/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBNotificationCenterWidgetHost <NSObject>
@optional
@property(assign, nonatomic) id<SBWidgetViewControllerDelegate> widgetDelegate;
- (void)hostDidDismiss;
- (void)hostDidPresent;
- (void)hostWillDismiss;
- (void)hostWillPresent;
@end

