/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBNotificationsBulletinInfo : SBBBBulletinInfo {
	SBNotificationsSectionInfo *_sectionInfo;
	float _heightForReusableView;
	CGSize _referenceSize;
	UIImage *_icon;
	UIImage *_attachmentImage;
	CGSize _attachmentImageSize;
	float _secondaryTextHeight;
	BOOL _suppressingMessageForPrivacy;
	BOOL _isCachedMessageSuppressionValid;
	UIColor *_secondaryTextColor;
}
@property(retain, nonatomic) UIImage *attachmentImage;
@property(assign, nonatomic) CGSize attachmentImageSize;
@property(retain, nonatomic) UIImage *icon;
@property(readonly, assign, nonatomic) UIColor *secondaryTextColor;
@property(retain, nonatomic) SBNotificationsSectionInfo *sectionInfo;
@property(readonly, assign, nonatomic, getter=isSuppressingMessageForPrivacy) BOOL suppressingMessageForPrivacy;
- (id)_attachmentImageToDisplay;
- (void)_configureEventDateLabel:(id)label;
- (void)_configureRelevanceDateLabel:(id)label;
- (CGSize)_effectiveAttachmentImageSize;
- (id)_endDate;
- (id)_eventDateLabel;
- (id)_eventDateLabelForDisplay;
- (BOOL)_isLayoutValidWithReferenceSize:(CGSize)referenceSize;
- (id)_primaryText;
- (id)_primaryTextColor;
- (id)_relevanceDateLabel;
- (XXStruct_Xx1ZfA)_relevanceDateLabelDescription;
- (id)_relevanceDateTextColor;
- (id)_secondaryText;
- (id)_secondaryTextColor;
- (id)_secondaryTextToDisplay;
- (id)_subtitleText;
- (id)_subtitleTextColor;
- (id)_subtitleTextToDisplay;
- (void)dealloc;
- (float)heightForReusableViewInTableView:(id)tableView;
- (id)identifier;
- (void)invalidateCachedLayoutData;
- (void)populateReusableView:(id)view;
- (Class)reusableViewClass;
@end

