/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBOrderedRequesters : XXUnknownSuperclass {
	NSMutableArray *_bands[3];
}
- (id)init;
- (void)addRequester:(id)requester toBand:(int)band;
- (BOOL)containsRequester:(id)requester inBand:(int)band;
- (void)dealloc;
- (id)description;
- (id)frontmostRequester;
- (void)prioritizeRequester:(id)requester;
- (void)removeRequester:(id)requester;
- (id)requesters;
@end

