/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBOrientationLockManager : XXUnknownSuperclass {
	int _override;
	int _lockedOrientation;
	int _overrideOrientation;
}
+ (id)sharedInstance;
- (void)_changeLockState:(id)state;
- (int)_deviceOrientationFromInterfaceOrientation:(int)interfaceOrientation;
- (int)_effectiveOrientation;
- (BOOL)_effectivelyLocked;
- (void)dealloc;
- (BOOL)isLocked;
- (void)lock;
- (void)lock:(int)lock;
- (int)lockOrientation;
- (int)lockOverride;
- (int)overrideOrientation;
- (void)restoreStateFromPrefs;
- (void)setLockOverride:(int)override orientation:(int)orientation;
- (void)unlock;
- (void)updateLockOverrideForCurrentDeviceOrientation;
@end

