/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWaveView.h"


@interface SBPathWaveView : SBWaveView {
}
+ (Class)layerClass;
- (id)initWithFrame:(CGRect)frame;
- (CGPathRef)_copyCurrentPath;
- (id)_shapeLayer;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (void)_updateCurrentPath;
- (void)layoutSubviews;
- (void)setColor:(id)color;
@end

