/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBTestRecipe.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBAppSwitcherTwoSectionFakeDataSource, NSString;
@protocol SBAppSwitcherPeopleDataSource;

__attribute__((visibility("hidden")))
@interface SBPeopleShuffleTestRecipe : XXUnknownSuperclass <SBTestRecipe> {
	BOOL _isUsingFakeDatasource;
	id<SBAppSwitcherPeopleDataSource> _realDatasource;
	SBAppSwitcherTwoSectionFakeDataSource *_fakeDataSource;
	int _upCount;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
+ (id)title;
- (id)init;
- (id)_peopleController;
- (void)_switchToFakeDatasource;
- (void)_switchToRealDatasource;
- (void)dealloc;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
@end

