/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertView.h"

@class NSTimer, TPBottomSingleButtonBar, TPTopLockBar, UIView;
@protocol SBPowerDownViewDelegate;

__attribute__((visibility("hidden")))
@interface SBPowerDownView : SBAlertView {
	id<SBPowerDownViewDelegate> _delegate;
	UIView *_dimView;
	TPTopLockBar *_lockView;
	TPBottomSingleButtonBar *_cancelView;
	NSTimer *_autoDismissTimer;
}
@property(assign, nonatomic) id<SBPowerDownViewDelegate> delegate;
- (id)initWithFrame:(CGRect)frame;
- (void)animateDark;
- (void)animateIn;
- (void)animateOut;
- (void)cancel:(id)cancel;
- (void)cancelAutoDismissTimer;
- (void)dealloc;
- (void)finishedAnimatingIn;
- (void)finishedAnimatingOut;
- (BOOL)isSupportedInterfaceOrientation:(int)orientation;
- (void)layoutForInterfaceOrientation:(int)interfaceOrientation;
- (void)lockBarStartedTracking:(id)tracking;
- (void)lockBarStoppedTracking:(id)tracking;
- (void)lockBarUnlocked:(id)unlocked;
- (void)notifyDelegateOfPowerDown;
- (void)powerDown:(id)down;
- (void)resetAutoDismissTimer;
@end

