/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBPreciseClockTimer : XXUnknownSuperclass {
	CADisplayLink *_displayLink;
	NSMutableDictionary *_minuteUpdateHandlers;
	unsigned _nextToken;
	NSCalendar *_calendar;
	int _lastHour;
	int _lastMinute;
}
+ (id)now;
+ (id)sharedInstance;
- (id)init;
- (void)_handleTimePassed;
- (void)_onDisplayLink:(id)link;
- (void)_updateDisplayLink;
- (void)_updateDisplayLinkFrameIntervalForSecondsPastMinute:(double)secondsPastMinute;
- (void)dealloc;
- (NSNumber *)startMinuteUpdatesWithHandler:(id)handler;
- (void)stopMinuteUpdatesForToken:(NSNumber *)token;
@end

