/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBReachabilityTriggerDelegate.h"

@class NSMutableSet, NSTimer, NSString, SBReachabilityTrigger;

__attribute__((visibility("hidden")))
@interface SBReachabilityManager : XXUnknownSuperclass <SBReachabilityTriggerDelegate> {
	NSMutableSet *_observers;
	BOOL _keepAliveForEndedInteraction;
	BOOL _reachabilityModeActive;
	BOOL _reachabilityModeEnabled;
	NSTimer *_keepAliveTimer;
	NSMutableSet *_temporaryDisabledReasons;
	SBReachabilityTrigger *_trigger;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL reachabilityEnabled;
@property(readonly, assign, nonatomic) BOOL reachabilityModeActive;
@property(readonly, assign) Class superclass;
+ (BOOL)reachabilitySupported;
+ (id)sharedInstance;
- (id)init;
- (void)_clearKeepAliveTimer;
- (void)_handleReachabilityActivated;
- (void)_handleReachabilityDeactivated;
- (void)_handleSignificantTimeChanged;
- (void)_keepAliveTimerFired:(id)fired;
- (void)_notifyObserversReachabilityModeActive:(BOOL)active excludingObserver:(id)observer;
- (void)_setKeepAliveTimerForDuration:(double)duration;
- (void)_toggleReachabilityModeWithRequestingObserver:(id)requestingObserver;
- (void)_updateReachabilityModeActive:(BOOL)active withRequestingObserver:(id)requestingObserver;
- (void)addObserver:(id)observer;
- (void)cancelPendingReachabilityRequests;
- (void)deactivateReachabilityModeForObserver:(id)observer;
- (void)dealloc;
- (void)disableExpirationTimerForInteraction;
- (void)enableExpirationTimerForEndedInteraction;
- (void)removeObserver:(id)observer;
- (void)setReachabilityTemporarilyDisabled:(BOOL)disabled forReason:(id)reason;
- (void)triggerDidTriggerReachability:(id)trigger;
@end

