/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBRelaunchAppWorkspaceTransaction : SBToAppsWorkspaceTransaction {
	BOOL _relaunchSuspended;
	BOOL _willBeOccluded;
	SBDisableActiveInterfaceOrientationChangeAssertion *_disableActiveOrientationChangeAssertion;
	SBStarkScreenController *_starkScreenController;
	SBWorkspaceApplication *_toApp;
}
@property(retain, nonatomic) SBStarkScreenController *starkScreenController;
- (id)initWithTransitionRequest:(id)transitionRequest;
- (id)_animationForApp:(id)app;
- (void)_begin;
- (void)_cleanUpAnimation;
- (void)_didComplete;
- (void)_handleAppRelaunch:(id)relaunch;
- (void)_handleApplicationUpdateScenesTransactionFailed:(id)failed;
- (id)_setupAnimation;
- (void)dealloc;
- (id)debugDescription;
@end

