/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBRemoteLocalNotificationAlertSheet : XXUnknownSuperclass {
	BOOL _lockToPortrait;
}
- (BOOL)requiresPortraitOrientation;
- (void)setLockToPortrait:(BOOL)portrait;
@end

