/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBRestoreFailureAlertItem : XXUnknownSuperclass {
}
- (void)_rebootNow;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (BOOL)allowInSetup;
- (BOOL)allowMenuButtonDismissal;
- (double)autoDismissInterval;
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
- (BOOL)forcesModalAlertAppearance;
- (void)performUnlockAction;
- (void)restartSystemEvent;
- (BOOL)shouldShowInLockScreen;
@end

