/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderController.h"


__attribute__((visibility("hidden")))
@interface SBRootFolderController : SBFolderController {
	BOOL _managesStatusBarWidth;
	UIWindow *_dockAnimationWindow;
}
@property(readonly, retain, nonatomic) SBRootFolderView *contentView;
@property(retain, nonatomic) UIWindow *dockAnimationWindow;
@property(assign, nonatomic) unsigned dockEdge;
@property(retain, nonatomic) SBRootFolder *folder;
@property(assign, nonatomic) BOOL managesStatusBarWidth;
+ (Class)listViewClass;
- (id)initWithFolder:(id)folder orientation:(int)orientation viewMap:(id)map;
- (CGRect)_autoscrollExclusionRegion;
- (void)_configureAppStatusBarInsets;
- (void)_configureAppStatusBarInsetsAnimated:(BOOL)animated;
- (void)_configureAppStatusBarInsetsForOrientation:(int)orientation;
- (void)_configureDockViewForOrientationDuringAnimation:(int)orientationDuringAnimation;
- (void)_configureDockViewForOrientationWithoutAnimation:(int)orientationWithoutAnimation;
- (void)_configureViewForOrientationWithoutAnimation:(int)orientationWithoutAnimation;
- (Class)_contentViewClass;
- (unsigned)_depth;
- (unsigned)_dockEdgeForInterfaceOrientation:(int)interfaceOrientation;
- (BOOL)_dockLayoutReversedForInterfaceOrientation:(int)interfaceOrientation;
- (BOOL)_isDockSwitchedForOrientation:(int)orientation;
- (BOOL)_listIndexIsVisible:(unsigned)visible;
- (BOOL)_shouldSlideDockOutDuringRotationFromOrientation:(int)orientation toOrientation:(int)orientation2;
- (BOOL)_shouldUseDockAnimationWindowForRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (void)addAdditionalInnerFolderAnimations;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
- (id)dockListView;
- (id)folderControllers;
- (BOOL)isDisplayingIcon:(id)icon;
- (BOOL)popFolderAnimated:(BOOL)animated completion:(id)completion;
- (void)prepareToClose;
- (void)prepareToOpen;
- (BOOL)pushFolder:(id)folder animated:(BOOL)animated completion:(id)completion;
- (BOOL)setCurrentPageIndex:(int)index animated:(BOOL)animated;
- (void)setDockOffscreenFraction:(float)fraction;
- (void)setDockVerticalStretch:(float)stretch;
- (void)setIdleText:(id)text;
- (UIEdgeInsets)statusBarInsetsForOrientation:(int)orientation;
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
@end

