/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBRoundedRectBorderView : XXUnknownSuperclass {
}
@property(retain, nonatomic) UIColor *borderColor;
@property(assign, nonatomic) float borderWidth;
@property(assign, nonatomic) float cornerRadius;
- (id)initWithFrame:(CGRect)frame;
- (void)dealloc;
@end

