/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconZoomAnimator.h"


__attribute__((visibility("hidden")))
@interface SBScaleIconZoomAnimator : SBIconZoomAnimator {
	UIEdgeInsets _iconScootch;
	float _dockStretch;
	SBIconCoordinate _dockListCenterCoordinate;
	SBIconCoordinate _mainListCenterCoordinate;
	float _naturalVisualAltitude;
	UIView *_scalingView;
	SBIcon *_targetIcon;
	float _zoomScale;
}
@property(readonly, assign, nonatomic) SBIcon *targetIcon;
@property(readonly, assign, nonatomic) SBIconView *targetIconView;
@property(readonly, assign, nonatomic) float zoomScale;
@property(retain, nonatomic) SBScaleZoomSettings *zoomSettings;
- (id)initWithFolderController:(id)folderController targetIcon:(id)icon;
- (void)_animateToZoomFraction:(float)zoomFraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
- (void)_applyOuterFadeFraction:(float)fraction;
- (void)_applyZoomFraction:(float)fraction;
- (void)_calculateIconScootch;
- (void)_cleanupZoom;
- (unsigned)_numberOfSignificantAnimations;
- (void)_prepareZoom;
- (CGPoint)_scootchForIcon:(id)icon inDock:(BOOL)dock;
- (void)_setZoomFraction:(float)fraction;
- (CGRect)_zoomedFrame;
- (CGPoint)_zoomedIconCenter;
- (float)_zoomedVisualAltitude;
- (void)dealloc;
@end

