/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSceneLayoutInterfaceOrientedView.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBSceneLayoutElementAnimationWrapperView : XXUnknownSuperclass <SBSceneLayoutInterfaceOrientedView> {
	SBLayoutElement *_layoutElement;
	SBAppView *_appView;
	SBOrientationTransformWrapperView *_orientedView;
	SBLayoutElementAdornmentView *_adornmentView;
}
@property(readonly, retain, nonatomic) SBLayoutElementAdornmentView *adornmentView;
@property(readonly, retain, nonatomic) SBAppView *appView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, retain, nonatomic) SBLayoutElement *layoutElement;
@property(readonly, assign, nonatomic) int layoutOrientation;
@property(readonly, assign) Class superclass;
- (id)initWithFrame:(CGRect)frame;
- (id)initWithLayoutElement:(id)layoutElement appView:(id)view;
- (id)initWithLayoutElement:(id)layoutElement appView:(id)view adornmentView:(id)view3;
- (void)dealloc;
- (void)invalidate;
- (void)layoutSubviews;
- (void)willMoveToSuperview:(id)superview;
@end

