/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SBSDaemonHandler : XXUnknownSuperclass {
}
+ (BOOL)addRequest:(id)request forKey:(id)key forDaemonPid:(int)daemonPid;
+ (void)initialize;
+ (void)noteDaemonCanceled:(id)canceled;
+ (void)removeRequestForKey:(id)key forDaemonPid:(int)daemonPid;
+ (id)stateDescription;
@end

