/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBSearchGesture : XXUnknownSuperclass <UIScrollViewDelegate> {
	NSHashTable *_observers;
	SBSearchScrollView *_scrollView;
	BOOL _suppressObserverCallbacks;
	BOOL _animatingReset;
	BOOL _enabled;
	UIView *_targetView;
}
@property(readonly, assign, nonatomic, getter=isAnimatingReset) BOOL animatingReset;
@property(assign, nonatomic) BOOL enabled;
@property(retain, nonatomic) UIView *targetView;
+ (id)sharedInstance;
- (id)init;
- (void)_displayLaunched:(id)launched;
- (void)_iconEditingStateChanged:(id)changed;
- (BOOL)_isShowingSearch;
- (void)_openFolderChanged:(id)changed;
- (void)_updateForFinalContentOffset;
- (void)_updateForScrollingEnded;
- (void)_updateScrollingEnabled;
- (void)addObserver:(id)observer;
- (void)dealloc;
- (void)removeObserver:(id)observer;
- (void)resetAnimated:(BOOL)animated;
- (void)scrollViewDidEndDecelerating:(id)scrollView;
- (void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndScrollingAnimation:(id)scrollView;
- (void)scrollViewDidScroll:(id)scrollView;
- (void)scrollViewDidScrollToTop:(id)scrollView;
- (void)scrollViewWillEndDragging:(id)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(inout CGPoint *)offset;
- (void)updateForRotation;
@end

