/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBSearchResultsDefaultAction : SBSearchResultsAction {
}
- (id)_launchingURLForResult:(id)result withDisplayIdentifier:(id)displayIdentifier andSection:(id)section;
- (id)performWithCompletionBlock:(id)completionBlock;
@end

