/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSearchStandardCell.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBSearchMailCell : SBSearchStandardCell {
}
+ (BOOL)supportsSection:(id)section result:(id)result;
- (id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
- (void)updateWithSection:(id)section result:(id)result traitCollection:(id)collection;
@end

