/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBSearchControllerWildcat : SBSearchController {
	void *_addressBook;
}
- (id)_auxiliaryTitleForABRecordID:(int)abrecordID;
- (void)_populateCell:(id)cell withSearchResult:(id)searchResult;
- (void)controllerWasDeactivated;
- (void)dealloc;
- (float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
@end

