/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBShowcaseController : XXUnknownSuperclass {
	UIWindow *_hostWindow;
	UIView *_hostView;
	UIWindow *_showcaseWindow;
	UIView *_rootView;
	UIView *_contentView;
	UIControl *_blockingView;
	UIView *_clippingView;
	UIView *_showcaseView;
	UIView *_topShadowView;
	UIView *_bottomShadowView;
	UIView *_hidingView;
	SBSlidingViewHighlight *_separator;
	float _revealAmount;
	int _orientation;
	BOOL _isAnimating;
	int _pendingRevealMode;
	id<SBShowcaseControllerOwner> _owner;
	id<SBShowcaseViewControllerProtocol> _showcaseViewController;
}
@property(assign, nonatomic, getter=isAnimating) BOOL animating;
@property(readonly, assign, nonatomic) UIControl *blockingView;
@property(retain, nonatomic) UIView *hidingView;
@property(retain, nonatomic) UIView *hostView;
@property(assign, nonatomic) int orientation;
@property(assign, nonatomic) id<SBShowcaseControllerOwner> owner;
@property(assign, nonatomic) float revealAmount;
@property(assign, nonatomic) int revealMode;
@property(retain, nonatomic) id<SBShowcaseViewControllerProtocol> showcase;
@property(readonly, assign, nonatomic) UIWindow *window;
+ (float)fullRevealAmount;
- (id)init;
- (CGRect)_adjustedContentFrameForFrame:(CGRect)frame;
- (CGRect)_contentFrame;
- (CGRect)_hostViewFrame;
- (CGRect)_portraitAdjustedFrameForFrame:(CGRect)frame;
- (CGAffineTransform)_rootTransform;
- (float)_separatorAlphaForRevealAmount:(float)revealAmount;
- (float)_showcaseRevealedAmount;
- (float)_showcaseWindowLevel;
- (void)_updateShowcase;
- (void)_updateShowcaseWindowLevel;
- (CGRect)_visibleShowcaseBounds;
- (float)bottomBarHeight;
- (void)dealloc;
- (void)didAppear;
- (void)didDisappear;
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
- (void)dismissWithAnimation:(BOOL)animation;
- (void)dismissWithFadeOfDuration:(double)duration;
- (void)noteRevealModeWillChange:(int)noteRevealMode;
- (float)revealAmountForMode:(int)mode;
- (void)setAlpha:(float)alpha;
- (void)setHidden:(BOOL)hidden;
- (CGRect)showcaseViewFrame;
- (BOOL)transferOwnershipToOwner:(id)owner;
- (void)updateRevealMode:(int)mode withBlock:(id)block;
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation;
- (void)willAppear;
- (void)willDisappear;
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation;
@end

