/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBSIMLockAlertItem : SBAlertItem {
	int _status;
	int _okButtonIndex;
	int _unlockButtonIndex;
}
+ (id)alertTitleForStatus:(int)status;
+ (id)alertTitleForStatus:(int)status languageCode:(id)code;
- (id)initWithStatus:(int)status;
- (id)alertTextForLanguageCode:(id)languageCode;
- (id)alertTitleForLanguageCode:(id)languageCode;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (BOOL)canUnlock;
- (void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
- (void)dealloc;
- (void)didDeactivateForReason:(int)reason;
- (id)lockLabel;
- (void)performUnlockAction;
- (int)status;
- (void)unlock;
@end

