/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSIMToolkitGetInputDisplay.h"


@interface SBSIMToolkitGetYesNoInputDisplay : SBSIMToolkitGetInputDisplay {
}
+ (id)newBottomBarForInstance:(id)instance;
- (void)noPressed:(id)pressed;
- (void)yesPressed:(id)pressed;
@end

