/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBSMSClass0AboutViewController : XXUnknownSuperclass {
	UITextView *_aboutContentView;
	UINavigationBar *_navigationBar;
}
- (void)dealloc;
- (void)doneButtonTapped:(id)tapped;
- (id)formattedAboutText;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
@end

