/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBSnakebiteGestureSettings : XXUnknownSuperclass {
	BOOL _showDebugRegions;
	float _maxDistanceFromDivider;
	float _maxHorizontalTouchDistance;
	float _minHorizontalTouchDistance;
	float _maxVerticalTouchDistance;
	float _maxSingleTouchDistanceFromDivider;
}
@property(assign, nonatomic) float maxDistanceFromDivider;
@property(assign, nonatomic) float maxHorizontalTouchDistance;
@property(assign, nonatomic) float maxSingleTouchDistanceFromDivider;
@property(assign, nonatomic) float maxVerticalTouchDistance;
@property(assign, nonatomic) float minHorizontalTouchDistance;
@property(assign, nonatomic) BOOL showDebugRegions;
+ (id)settingsControllerModule;
- (void)setDefaultValues;
@end

