/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBPasscodeEntryAlertViewDelegate.h"
#import "SpringBoard-Structs.h"
#import "SBPasscodeEntryAlertViewController.h"

@protocol SBPasscodeEntryAlertViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBSoftwareUpdateAuthenticationAlertViewController : SBPasscodeEntryAlertViewController <SBPasscodeEntryAlertViewDelegate> {
	id _completionBlock;
	SUDocumentation *_documentation;
	NSString *_passcode;
	UINavigationController *_termsAndConditionsController;
	BOOL _showingTermsAndConditions;
	id<SBPasscodeEntryAlertViewControllerDelegate> _delegate;
}
@property(copy, nonatomic) id completion;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, retain, nonatomic) SUDocumentation *documentation;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
- (id)initWithDocumentation:(id)documentation;
- (void)_authenticationCancelled;
- (void)_authenticationSuccess:(id)success fromMesa:(BOOL)mesa;
- (void)_configurePasscodeView:(id)view;
- (void)_dismissSelf:(BOOL)aSelf;
- (void)_dismissTermsAndConditionsIfNecessaryAnimated:(BOOL)animated withCompletion:(id)completion;
- (void)_presentTermsAndConditions:(id)conditions completion:(id)completion;
- (void)_presentTermsAndConditionsOrDismissAfterDelay:(BOOL)delay completion:(id)completion;
- (void)_sendCompletionResponse:(BOOL)response;
- (void)_sendDeactivationResponseFailureIfNecessary;
- (BOOL)_shouldShowPasscodeView;
- (void)_termsAgree;
- (void)_termsDisagree;
- (id)alertDisplayViewWithSize:(CGSize)size;
- (void)deactivate;
- (void)dealloc;
- (id)delegate;
- (BOOL)passcodeAlertViewShouldShowAutomaticallyWhenVisible:(id)passcodeAlertView;
- (void)setDelegate:(id)delegate;
- (void)setVisible:(BOOL)visible animated:(BOOL)animated completion:(id)completion;
- (BOOL)suppressesBanners;
- (BOOL)suppressesControlCenter;
- (BOOL)suppressesNotificationCenter;
- (BOOL)suppressesSiri;
@end

