/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSHashTable, NSMutableDictionary, AVController, NSMutableArray, SBUISound;

__attribute__((visibility("hidden")))
@interface SBSoundController : XXUnknownSuperclass {
	NSMutableDictionary *_soundsBySystemSoundIDs;
	AVController *_ringtoneController;
	id _ringtoneObserver;
	SBUISound *_ringtoneSound;
	NSHashTable *_observers;
	unsigned _pendingCallbacks;
	NSMutableArray *_pendedCallbacks;
}
+ (id)sharedInstance;
- (id)init;
- (void)_beginPendingCallbacksBlock;
- (void)_cleanupSystemSound:(unsigned long)sound andKill:(BOOL)kill;
- (void)_endPendingCallbacksBlock;
- (void)_enqueueCallback:(id)callback;
- (void)_killRingtone;
- (BOOL)_playRingtone:(id)ringtone;
- (BOOL)_playSystemSound:(id)sound;
- (void)_ringerStateChanged:(id)changed;
- (void)_soundDidFinishPlaying:(id)_sound;
- (void)_soundDidStartPlaying:(id)_sound;
- (BOOL)_stopAllSounds;
- (void)addObserver:(id)observer;
- (void)dealloc;
- (BOOL)handleVolumeButtonDownEvent;
- (BOOL)isPlaying:(id)playing;
- (BOOL)isPlayingAnySound;
- (BOOL)playSound:(id)sound;
- (BOOL)playSound:(id)sound completion:(id)completion;
- (void)removeObserver:(id)observer;
- (void)stopAllSounds;
- (void)stopSound:(id)sound;
@end

