/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBStatusBarNoServiceView : SBStatusBarContentView {
	NSString *_errorString;
}
+ (id)displayStringForRegistrationStatus:(int)registrationStatus;
+ (id)displayStringForSIMStatus:(id)simstatus;
- (id)initWithErrorString:(id)errorString;
- (void)dealloc;
- (void)drawRect:(CGRect)rect;
- (id)errorString;
- (GSFontRef)textFont;
@end

