/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBStatusBarContentView.h"

@class NSString;

@interface SBStatusBarOperatorNameView : SBStatusBarContentView {
	float _letterSpacing;
	NSString *_operatorName;
	BOOL _fullSize;
}
- (id)initWithOperatorName:(id)operatorName;
- (float)calculateLetterSpacingForOperatorName:(id)operatorName;
- (void)dealloc;
- (void)drawRect:(CGRect)rect;
- (id)operatorName;
- (void)setOperatorName:(id)name fullSize:(BOOL)size;
@end

