/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLayoutState.h"


__attribute__((visibility("hidden")))
@interface SBStarkLayoutState : SBLayoutState {
}
+ (int)_defaultOrientation;
- (id)_initWithElements:(id)elements interfaceOrientation:(int)orientation;
@end

