/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBStarkAppToAppWorkspaceTransactionFactory : XXUnknownSuperclass {
}
+ (id)newTransactionWithMainDisplayTransitionRequest:(id)mainDisplayTransitionRequest starkScreenController:(id)controller underLock:(BOOL)lock;
@end

