/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBStatusBarStyleOverridesSettings : XXUnknownSuperclass {
	BOOL _exclusive;
	BOOL _showsWhenForeground;
	int _styleOverride;
}
@property(assign, nonatomic) BOOL exclusive;
@property(assign, nonatomic) BOOL showsWhenForeground;
@property(assign, nonatomic) int styleOverride;
+ (id)settingsControllerModule;
- (void)setDefaultValues;
@end

