/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "RadiosPreferencesDelegate.h"

@class NSDateFormatter, RadiosPreferences, NSString, NSTimer;

@interface SBStatusBarDataManager : XXUnknownSuperclass <RadiosPreferencesDelegate> {
	struct {
		BOOL itemIsEnabled[22];
		BOOL timeString[64];
		int gsmSignalStrengthRaw;
		int gsmSignalStrengthBars;
		BOOL serviceString[100];
		BOOL serviceImageBlack[100];
		BOOL serviceImageSilver[100];
		BOOL operatorDirectory[1024];
		unsigned serviceContentType;
		int wifiSignalStrengthRaw;
		int wifiSignalStrengthBars;
		unsigned dataNetworkType;
		int batteryCapacity;
		unsigned batteryState;
		BOOL notChargingString[150];
		int bluetoothBatteryCapacity;
		int thermalColor;
		unsigned thermalSunlightMode : 1;
		unsigned slowActivity : 1;
		BOOL activityDisplayId[256];
		unsigned bluetoothConnected : 1;
		unsigned displayRawGSMSignal : 1;
		unsigned displayRawWifiSignal : 1;
	} _data;
	int _actions;
	BOOL _itemIsEnabled[22];
	BOOL _itemIsCloaked[22];
	int _updateBlockDepth;
	BOOL _dataChangedSinceLastPost;
	NSDateFormatter *_timeItemDateFormatter;
	NSTimer *_timeItemTimer;
	NSString *_timeItemTimeString;
	RadiosPreferences *_radiosPrefs;
	BOOL _cellRadio;
	BOOL _registered;
	BOOL _simError;
	BOOL _simulateInCallStatusBar;
	NSString *_serviceString;
	NSString *_serviceImageBlack;
	NSString *_serviceImageSilver;
	NSString *_operatorDirectory;
	BOOL _showsActivityIndicatorOnHomeScreen;
	int _thermalColor;
	BOOL _thermalSunlightMode;
	NSString *_recordingAppString;
	BOOL _showingNotChargingItem;
	NSString *_notChargingString;
}
+ (id)sharedDataManager;
- (id)init;
- (void)_batteryStatusChange;
- (void)_bluetoothBatteryChange;
- (void)_bluetoothChange;
- (void)_callForwardingChange;
- (void)_configureTimeItemDateFormatter;
- (void)_dataChanged;
- (void)_dataNetworkChange;
- (void)_didWakeFromSleep;
- (id)_displayStringForRegistrationStatus:(int)registrationStatus;
- (id)_displayStringForSIMStatus:(id)simstatus;
- (void)_getBlackImageName:(id *)name silverImageName:(id *)name2 directory:(id *)directory forFakeCarrier:(id)fakeCarrier;
- (BOOL)_getBlackImageName:(id *)name silverImageName:(id *)name2 directory:(id *)directory forOperator:(id)anOperator statusBarCarrierName:(id *)name5;
- (void)_initializeData;
- (void)_locationStatusChange;
- (void)_notChargingStatusChange;
- (void)_operatorChange;
- (void)_postData;
- (void)_registerForNotifications;
- (void)_restartTimeItemTimer;
- (void)_rotationLockChange;
- (BOOL)_shouldShowNotChargingItem;
- (void)_signalStrengthChange;
- (void)_significantTimeOrLocaleChange;
- (void)_stopTimeItemTimer;
- (void)_ttyChange;
- (void)_updateActivityItem;
- (void)_updateAirplaneMode;
- (void)_updateBatteryItem;
- (void)_updateBatteryPercentItem;
- (void)_updateBluetoothBatteryItem;
- (void)_updateBluetoothItem;
- (void)_updateCallForwardingItem;
- (void)_updateDataNetworkItem;
- (void)_updateLocationItem;
- (void)_updateNotChargingItem;
- (void)_updateNotChargingItemAfterDelay;
- (void)_updatePlayItem;
- (void)_updateRotationLockItem;
- (void)_updateServiceItem;
- (void)_updateSignalStrengthItem;
- (void)_updateTTYItem;
- (void)_updateTelephonyState;
- (void)_updateThermalColorItem;
- (void)_updateTimeItem;
- (void)_updateTimeString;
- (void)_updateVPNItem;
- (void)_vpnChange;
- (void)airplaneModeChanged;
- (void)beginUpdateBlock;
- (void)dealloc;
- (void)enableLock:(BOOL)lock time:(BOOL)time;
- (void)endUpdateBlock;
- (void)sendStatusBarActions:(int)actions;
- (void)setAllItemsExceptBatteryCloaked:(BOOL)cloaked;
- (void)setShowsActivityIndicatorOnHomeScreen:(BOOL)screen;
- (void)setStatusBarItem:(int)item cloaked:(BOOL)cloaked;
- (void)setStatusBarItem:(int)item enabled:(BOOL)enabled;
- (void)setTelephonyAndBluetoothItemsCloaked:(BOOL)cloaked;
- (void)setThermalColor:(int)color sunlightMode:(BOOL)mode;
- (void)toggleSimulatesInCallStatusBar;
- (void)updateStatusBarItem:(int)item;
@end

