/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWorkspaceTransitionRequest.h"


__attribute__((visibility("hidden")))
@interface SBStarkWorkspaceTransitionRequest : SBWorkspaceTransitionRequest {
	SBStarkScreenController *_screenController;
}
@property(retain, nonatomic) SBStarkScreenController *screenController;
+ (id)requestWithScreenController:(id)screenController;
- (id)initWithScreenController:(id)screenController;
- (id)initWithWorkspace:(id)workspace display:(id)display;
- (void)dealloc;
@end

