/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkBannerItem.h"


__attribute__((visibility("hidden")))
@interface SBStarkBulletinBannerItem : SBStarkBannerItem {
	BBBulletin *_bulletin;
	SBUISound *_sound;
	unsigned _feed;
}
- (id)initWithBulletin:(id)bulletin feed:(unsigned)feed;
- (id)action;
- (id)categoryImage;
- (void)dealloc;
- (int)defaultActionType;
- (id)ignoreAction;
- (BOOL)matchesContext:(id)context;
- (id)sound;
- (id)sourceDate;
- (id)subActionLabels;
- (id)subActionWithIndex:(unsigned)index;
- (id)subTitle;
- (id)title;
- (void)updateBulletinToInstance:(id)instance;
@end

