/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSwitcherWallpaperPageContentView.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBSwitcherMetahostingHomePageContentView : SBSwitcherWallpaperPageContentView {
	SBOrientationTransformWrapperView *_portraitContentWrapper;
	SBOrientationTransformWrapperView *_rotatingContentWrapper;
	UIView *_darkeningView;
	SBWindowSelfHostWrapper *_iconsWindowHostWrapper;
	UIView *_snapshotView;
	UIView *_fakeStatusBarWrapper;
	SBFakeStatusBarView *_fakeStatusBar;
	SBAppSwitcherSettings *_settings;
	BOOL _presenting;
	BOOL _interactive;
}
+ (BOOL)_usesSnapshots;
- (id)initWithFrame:(CGRect)frame;
- (void)_createFakeStatusBar;
- (float)_darkeningFactor;
- (void)_layoutFakeStatusBar;
- (void)_removeSnapshotIfNecessary;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (void)_substituteSnapshotIfNecessary;
- (int)_targetWallpaperStyle;
- (void)_transitionWallpaperWithProgress:(float)progress presenting:(BOOL)presenting;
- (float)cornerRadius;
- (void)dealloc;
- (void)interactionDidEnd:(BOOL)interaction;
- (void)layoutSubviews;
- (void)setCornerRadius:(float)radius;
- (void)setOrientation:(int)orientation;
- (void)transitionDidEnd:(BOOL)transition forPresentation:(BOOL)presentation;
- (void)updateTransitionProgress:(float)progress;
- (void)viewDismissing:(id)dismissing withInteraction:(BOOL)interaction andInitialProgress:(float)progress forTransitionRequest:(id)transitionRequest;
- (void)viewPresenting:(id)presenting withInteraction:(BOOL)interaction andInitialProgress:(float)progress forTransitionRequest:(id)transitionRequest;
- (void)willMoveToWindow:(id)window;
@end

