/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBSwitcherContainerView : XXUnknownSuperclass {
	UIView *_contentView;
}
@property(retain, nonatomic) UIView *contentView;
- (void)dealloc;
- (void)layoutSubviews;
@end

