/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBSystemGestureWorkspaceTransaction : SBMainWorkspaceTransaction <FBSynchronizedTransactionDelegate> {
	NSString *_suppressionReason;
	UIGestureRecognizer *_gestureRecognizer;
	int _completionType;
	NSMutableSet *_nonSlaveChildrenWaitingToFinish;
	BOOL _notifiedSlaves;
}
@property(readonly, assign, nonatomic) int completionType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) UIGestureRecognizer *gestureRecognizer;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
- (id)initWithTransitionRequest:(id)transitionRequest;
- (void)_begin;
- (void)_beginAnimation;
- (void)_childTransactionDidComplete:(id)_childTransaction;
- (void)_didComplete;
- (void)_finishWithCompletionType:(int)completionType;
- (void)_notifySlavesForMilestoneRemovalIfNecessary;
- (void)_notifySlavesIfNecessary;
- (void)_setupAnimation;
- (void)_willAddChildTransaction:(id)transaction;
- (void)addSlaveTransaction:(id)transaction;
- (void)dealloc;
- (void)finishWithCompletionType:(int)completionType;
- (void)removeAllMilestones;
- (BOOL)removeMilestone:(id)milestone;
- (BOOL)removeMilestones:(id)milestones;
- (void)synchronizedTransaction:(id)transaction didCommitSynchronizedTransactions:(id)transactions;
- (void)synchronizedTransaction:(id)transaction willCommitSynchronizedTransactions:(id)transactions;
- (void)synchronizedTransactionReadyToCommit:(id)commit;
- (void)systemGestureStateChanged:(id)changed;
@end

