/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBTetheringCell : SBWirelessCell {
	UIImageView *_icon;
}
- (id)initWithDictionary:(id)dictionary;
- (void)dealloc;
- (void)setInProgress:(BOOL)progress;
@end

