/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBTodayViewSettingsViewController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource> {
	id<SBTodayViewSettingsViewControllerDelegate> _settingsViewControllerDelegate;
	UINavigationController *_navigationController;
	UITableViewController *_tableViewController;
	NSMutableArray *_enabledTodayItems;
	NSMutableArray *_enabledWidgetItems;
	NSMutableArray *_disabledItems;
	SBInterfaceItemInfo *_todayItem;
	SBInterfaceItemInfo *_tomorrowItem;
	SBInterfaceItemInfo *_coreRoutineItem;
	BOOL _coreRoutineIsAvailable;
	NSArray *_groupIDs;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
- (id)initWithSettingsViewControllerDelegate:(id)settingsViewControllerDelegate;
- (void)_acknowledgeInterfaceItemsAndResetNewWidgetsCount;
- (void)_cancelWidgetsSettings;
- (void)_cancelWidgetsSettingsAcknowledgingInterfaceItemsAndResettingNewWidgetsCount:(BOOL)count;
- (int)_compareInterfaceItem:(id)item andInterfaceItemConsideringIsNew:(id)aNew;
- (void)_disableItemAtIndexPath:(id)indexPath inTableView:(id)tableView;
- (void)_dismissWidgetsSettings;
- (void)_enableItemAtIndexPath:(id)indexPath inTableView:(id)tableView;
- (id)_enabledItemsForGroupID:(id)groupID;
- (id)_groupKeyForSectionAtIndex:(unsigned)index;
- (unsigned)_indexForInsertingItem:(id)insertingItem intoArray:(id)array;
- (int)_indexOfFirstEnabledWidgetInSection:(unsigned)section;
- (int)_indexOfLastEnabledWidgetInSection:(unsigned)section;
- (id)_interfaceItemForIndexPath:(id)indexPath;
- (id)_interfaceItemsInSection:(unsigned)section;
- (BOOL)_isFixedSnippetsItem:(id)item;
- (BOOL)_isNewInterfaceItem:(id)item;
- (int)_layoutMode;
- (void)_loadInterfaceItems;
- (id)_newBackgroundView;
- (void)_saveInterfaceItemsArrangement;
- (void)_saveInterfaceItemsState;
- (unsigned)_sectionIndexForGroupKey:(id)groupKey;
- (BOOL)_updateCoreRoutineAvailability;
- (void)dealloc;
- (int)numberOfSectionsInTableView:(id)tableView;
- (BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
- (BOOL)tableView:(id)view canMoveRowAtIndexPath:(id)indexPath;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
- (void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
- (void)tableView:(id)view didEndReorderingRowAtIndexPath:(id)indexPath;
- (int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
- (void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
- (int)tableView:(id)view numberOfRowsInSection:(int)section;
- (BOOL)tableView:(id)view shouldDrawTopSeparatorForSection:(int)section;
- (BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;
- (id)tableView:(id)view targetIndexPathForMoveFromRowAtIndexPath:(id)indexPath toProposedIndexPath:(id)proposedIndexPath;
- (id)tableView:(id)view titleForDeleteConfirmationButtonForRowAtIndexPath:(id)indexPath;
- (id)tableView:(id)view titleForHeaderInSection:(int)section;
- (id)tableView:(id)view viewForHeaderInSection:(int)section;
- (void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillLayoutSubviews;
@end

