/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBTransientActiveInterfaceOrientationRequester : XXUnknownSuperclass {
	int _orientation;
	NSString *_reason;
}
@property(readonly, assign, nonatomic) int orientation;
@property(readonly, assign, nonatomic) NSString *reason;
- (id)initWithOrientation:(int)orientation andReason:(id)reason;
- (void)dealloc;
@end

