/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


__attribute__((visibility("hidden")))
@interface SBUIFullscreenAlertAdapter : SBAlert {
	SBUIFullscreenAlertController *_alertController;
	SBAlertView *_alertDisplay;
	BOOL _animatingDeactivation;
}
- (id)initWithAlertController:(id)alertController;
- (void)_pluginViewAnimatedOut:(id)anOut;
- (void)_updateForTransparentDismiss:(id)transparentDismiss;
- (id)alertController;
- (id)alertDisplayViewWithSize:(CGSize)size;
- (void)alertWindow:(id)window didRotateFromInterfaceOrientation:(int)interfaceOrientation;
- (void)alertWindow:(id)window resizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame3;
- (void)alertWindow:(id)window willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (void)alertWindow:(id)window willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (BOOL)allowsEventOnlySuspension;
- (BOOL)allowsStackingOfAlert:(id)alert;
- (void)animateViewOut;
- (BOOL)currentlyAnimatingDeactivation;
- (void)dealloc;
- (id)description;
- (BOOL)dismissPresentedModalAlertIfNecessary;
- (void)handleAutoLock;
- (BOOL)handleHeadsetButtonPressed:(BOOL)pressed;
- (BOOL)handleLockButtonPressed;
- (BOOL)handleMenuButtonTap;
- (BOOL)handleVolumeDownButtonPressed;
- (BOOL)handleVolumeUpButtonPressed;
- (BOOL)hasTranslucentBackground;
- (void)launchSucceeded:(BOOL)succeeded;
- (void)prepareViewToAnimateOut;
- (void)presentAlertModally:(id)modally;
- (void)setViewShouldAnimateIn:(BOOL)animateIn;
- (BOOL)viewDisplaysAboveStatusBar;
- (BOOL)viewIsReadyToBeRemoved;
@end

