/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBUIRemoteAlertServiceInterface
@optional
- (void)handleDoubleHeightStatusBarTap;
- (void)handleHeadsetButtonPressed:(BOOL)pressed;
- (void)handleHomeButtonPressed;
- (void)handleLockButtonPressed;
- (void)handleVolumeDownButtonPressed;
- (void)handleVolumeUpButtonPressed;
- (void)noteActivatedForCustomReason:(id)customReason;
- (void)setUserInfo:(id)info;
@end

