/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"


__attribute__((visibility("hidden")))
@interface SBUIAnimationFadeAppToRemoteAlert : SBUIMainScreenAnimationController {
	SBRemoteAlertAdapter *_alert;
	SBAlertManager *_alertManager;
	UIView *_appContextHostView;
	UIView *_alertContextHostView;
	NSArray *_accessoryHostViews;
}
- (id)initWithAlert:(id)alert deactivatingApp:(id)app alertManager:(id)manager;
- (void)_animationFinished;
- (void)_cleanupAnimation;
- (id)_getTransitionWindow;
- (void)_prepareAnimation;
- (void)_setHidden:(BOOL)hidden;
- (void)_startAnimation;
- (double)animationDuration;
- (void)dealloc;
@end

