/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class UIView, SBDosidoAnimator, SBUIAnimationWindow;

__attribute__((visibility("hidden")))
@interface SBUIAnimationDosidoTransitionController : SBUIMainScreenAnimationController {
	SBUIAnimationWindow *_transitionWindow;
	UIView *_fromAppContextHostView;
	UIView *_fromView;
	UIView *_toView;
	SBDosidoAnimator *_dosidoAnimator;
	int _fromOrientation;
	BOOL _fromNC;
	BOOL _fromCC;
	BOOL _fromAssistant;
	BOOL _requiresHostView;
}
- (id)initWithActivatingApp:(id)activatingApp deactivatingApp:(id)app;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (void)_cleanupAnimation;
- (id)_getTransitionWindow;
- (void)_kickOffAnimation;
- (void)_performDosido;
- (void)_prepareAnimation;
- (void)_setFromView:(id)view;
- (void)_setHidden:(BOOL)hidden;
- (void)_startAnimation;
- (void)captureFlagsForActivatingDisplay:(id)activatingDisplay;
- (void)dealloc;
- (void)hideRealFromView;
- (int)orientationAtLaunch;
- (void)setToView:(id)view;
@end

