/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBUIBannerSourceManager <NSObject>
- (id)currentBannerItemForSource:(id)source;
- (void)dismissCurrentBannerItemForSource:(id)source;
- (void)registerSource:(id)source;
- (void)signalSource:(id)source;
- (void)unregisterSource:(id)source;
@end

