/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */


@protocol SBUIAnimationControllerGroupDelegate;

__attribute__((visibility("hidden")))
@interface SBUIAnimationControllerGroup : SBUIAnimationController <SBUIAnimationControllerDelegate> {
	NSMutableArray *_animations;
	BOOL _finished;
}
@property(readonly, assign, nonatomic) NSArray *animations;
@property(assign, nonatomic) id<SBUIAnimationControllerGroupDelegate> delegate;
- (id)init;
- (id)initWithAnimations:(id)animations;
- (void)_forEachAnimation:(id)eachAnimation;
- (void)_startAnimation;
- (BOOL)_willAnimate;
- (void)addAnimation:(id)animation;
- (void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
- (void)animationControllerDidFinishAnimation:(id)animationController;
- (void)beginAnimation;
- (void)dealloc;
- (id)description;
- (void)endAnimation;
- (BOOL)waitingToStart;
@end

