/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"


__attribute__((visibility("hidden")))
@interface SBUIAnimationDosidoTransitionController : SBUIMainScreenAnimationController {
	UIView *_fromView;
	UIView *_toView;
	SBWindowSelfHostWrapper *_homeScreenHostWrapper;
	SBDosidoAnimator *_dosidoAnimator;
	int _fromOrientation;
	BOOL _requiresHostView;
	BOOL _fromAppWantsLiveContent;
	BOOL _dosidoDidComplete;
	BOOL _crossfadeDidComplete;
	BOOL _activationFailed;
	BOOL _finishedActivating;
	unsigned _direction;
	SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
}
@property(assign, nonatomic) unsigned direction;
@property(assign, nonatomic) BOOL fromAppWantsLiveContent;
- (id)initWithTransitionContextProvider:(id)transitionContextProvider;
- (id)_animationFactory;
- (id)_animationProgressDependencies;
- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (id)_getTransitionWindow;
- (void)_invalidateWrapperView:(id)view;
- (BOOL)_isTransitionFromSpotlight;
- (BOOL)_isTransitionToSpotlight;
- (void)_kickOffAnimation;
- (id)_mainScreenSnapshot;
- (void)_maybeReportAnimationFinished;
- (void)_maybeStartCrossfade;
- (void)_performCrossfadeIfNeeded;
- (void)_performDosido;
- (void)_prepareAnimation;
- (void)_setFromView:(id)view;
- (void)_setHidden:(BOOL)hidden;
- (void)_setupDisplayModeForActivatingAppView:(id)activatingAppView;
- (void)_setupDisplayModeForAppView:(id)appView displayMode:(int)mode;
- (void)_setupDisplayModeForDeactivatingAppView:(id)deactivatingAppView;
- (void)_startAnimation;
- (BOOL)_waitsForApplicationActivationIfNecessary;
- (void)captureFlagsForActivatingApp:(id)activatingApp;
- (void)dealloc;
- (void)enableSteppingWithAnimationSettings:(id)animationSettings;
- (BOOL)isReasonableMomentToInterrupt;
- (int)orientationAtLaunch;
- (void)setToView:(id)view;
@end

