/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBUIController : NSObject {
	UIWindow *_window;
	UIView *_iconsView;
	UIView *_buttonBarContainerView;
	SBContentLayer *_contentLayer;
	SBZoomView *_zoomLayer;
	SBApplication *_launchedApp;
	int _launchState;
	BOOL _lastVolumeDownToControl;
	BOOL _shouldAutoLock;
	int _batteryCapacity;
	BOOL _isBatteryCharging;
	BOOL _isOnAC;
	BOOL _connectedToUnusableFirewire;
	BOOL _cancelingLaunch;
	int _batteryLoggingStartCapacity;
	unsigned char _headsetBatteryCapacity;
	BOOL _isHeadsetCharging;
	BOOL _isHeadsetDocked;
}
+ (int)displayedLevelForBatteryLevel:(int)batteryLevel;
+ (int)displayedLevelForBatteryStatusBarLevel:(int)batteryStatusBarLevel;
+ (id)sharedInstance;
- (id)init;
- (void)ACPowerChanged;
- (void)_indicateConnectedToPower;
- (CGAffineTransform)_initialStatusBarTransformForScale:(float)scale;
- (void)animateAppleDown:(BOOL)down;
- (void)animateLaunchApplication:(id)application;
- (double)animateLaunchForReturnToLastApp:(id)lastApp;
- (void)animateLaunchOfApplication:(id)application;
- (void)animateLaunchOfApplication:(id)application afterDelay:(double)delay startingAtTime:(double)time forDuration:(double)duration includingIconsAndButtonBar:(BOOL)bar initialZoomScale:(float)scale fadeInZoom:(BOOL)zoom;
- (int)batteryCapacity;
- (float)calculateStartupTime;
- (void)cancelLaunchAnimationDidStop:(id)cancelLaunchAnimation finished:(id)finished;
- (void)cancelLaunchOfApplication:(id)application duration:(double)duration;
- (void)clearLaunchedAfterLanguageRestart;
- (void)clearZoomLayer;
- (void)clickedMenuButton;
- (void)completeAlertDisplay;
- (id)contentView;
- (void)dealloc;
- (void)finishLaunching;
- (void)finishedFadingInButtonBar;
- (id)getVMstats;
- (void)handleAccessoryAvailabilityChange:(GSEventRef)change removal:(BOOL)removal;
- (void)handleAccessoryEvent:(GSEventRef)event;
- (void)handleVolumeEvent:(GSEventRef)event;
- (unsigned char)headsetBatteryCapacity;
- (void)hideIconListAndBar:(BOOL)bar;
- (void)insertAndOrderIconListsForReordering:(BOOL)reordering;
- (BOOL)isBatteryCharging;
- (BOOL)isConnectedToUnusableFirewireCharger;
- (BOOL)isHeadsetBatteryCharging;
- (BOOL)isHeadsetDocked;
- (BOOL)isOnAC;
- (void)languageChanged;
- (int)launchState;
- (BOOL)launchedAfterLanguageRestart;
- (void)lock;
- (void)lock:(BOOL)lock;
- (void)logStartupData;
- (void)noteStatusBarHeightChanged:(float)changed duration:(double)duration;
- (void)quitTopApplication;
- (void)restoreIconList:(BOOL)list force:(BOOL)force;
- (void)setIsConnectedToUnusableFirewireCharger:(BOOL)unusableFirewireCharger;
- (void)setState:(int)state;
- (void)showButtonBar:(BOOL)bar animate:(BOOL)animate action:(SEL)action delegate:(id)delegate;
- (void)showZoomLayerAnimationDidStop:(id)showZoomLayerAnimation finished:(id)finished;
- (void)showZoomLayerForApp:(id)app;
- (id)statusBarWindow;
- (void)stopAllAnimations;
- (void)stopRestoringIconList;
- (void)systemControllerRouteChanged:(id)changed;
- (void)wakeUp:(id)up;
- (id)window;
@end

@interface SBUIController (SBHIDInterface)
- (void)displayTouchPoints;
@end

@interface SBUIController (ShowTouchPoints)
- (void)showTouchPoints:(void *)points;
@end

