/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAlert, SBLockScreenViewController, SBAlertManager;

__attribute__((visibility("hidden")))
@interface SBUIAnimationFadeAlertToLockscreen : SBUIMainScreenAnimationController {
	SBLockScreenViewController *_lockScreenViewController;
	SBAlert *_deactivatingAlert;
	SBAlertManager *_alertManager;
}
- (id)initWithLockScreenController:(id)lockScreenController deactivatingAlert:(id)alert alertManager:(id)manager;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (void)_startAnimation;
- (double)animationDelay;
- (double)animationDuration;
- (void)dealloc;
@end

