/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBUIAnimationController : XXUnknownSuperclass {
	id<SBUIAnimationControllerDelegate> _delegate;
	UIWindow *_transitionWindow;
	UIView *_transitionContainer;
	SBApplication *_activatingApp;
	SBApplication *_deactivatingApp;
	SBActivationContext *_activatingContext;
	SBActivationContext *_deactivatingContext;
	BKSApplicationActivationAssertion *_activationAssertion;
	id _commitBlock;
	int _animationState;
	BOOL _cancelOnNextSuspendIfNecessary;
	BOOL _didPostBeginAnimationNotification;
	BOOL _didNotifyDelegateOfCompletion;
	BOOL _needsCATransactionActivate;
}
@property(retain, nonatomic) SBApplication *activatingApp;
@property(retain, nonatomic) SBActivationContext *activatingContext;
@property(retain, nonatomic) BKSApplicationActivationAssertion *activationAssertion;
@property(assign, nonatomic) BOOL cancelOnNextSuspendIfNecessary;
@property(copy, nonatomic) id commitBlock;
@property(readonly, assign, nonatomic) UIView *containerView;
@property(retain, nonatomic) SBApplication *deactivatingApp;
@property(retain, nonatomic) SBActivationContext *deactivatingContext;
@property(assign, nonatomic) id<SBUIAnimationControllerDelegate> delegate;
@property(assign, nonatomic) BOOL needsCATransactionActivate;
- (id)init;
- (id)initWithActivatingApp:(id)activatingApp deactivatingApp:(id)app;
- (void)__cancelAnimation;
- (void)__cleanupAnimation;
- (void)__noteAnimationDidTerminateWithSuccess:(BOOL)__noteAnimation;
- (void)__startAnimation;
- (id)_animationIdentifier;
- (id)_animationProgressDependency;
- (BOOL)_animationShouldStart;
- (int)_animationState;
- (void)_applicationActivationStateDidChange;
- (void)_applicationDependencyStateChanged;
- (void)_cancelAnimation;
- (void)_cleanupAnimation;
- (void)_evaluateProgressConditions;
- (id)_getTransitionWindow;
- (BOOL)_isNullAnimation;
- (void)_noteAnimationDidCommit:(BOOL)_noteAnimation withDuration:(double)duration afterDelay:(double)delay;
- (void)_noteAnimationDidFail;
- (void)_noteAnimationDidFinish;
- (void)_notifyDelegateOfCompletion;
- (void)_prepareAnimation;
- (void)_releaseActivationAssertion;
- (void)_setAnimationState:(int)state;
- (void)_setHidden:(BOOL)hidden;
- (BOOL)_shouldDismissBanner;
- (BOOL)_shouldTakeActivationAssertionForDeactivatingApp;
- (void)_startAnimation;
- (BOOL)_willAnimate;
- (BOOL)animating;
- (void)beginAnimation;
- (void)dealloc;
- (void)endAnimation;
- (BOOL)isComplete;
- (BOOL)isReasonableMomentToInterrupt;
- (BOOL)waitingToStart;
@end

