/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAppViewHostRequester.h"
#import "SBUIMainScreenAnimationController.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBUIDismissSwitcherAnimationController : SBUIMainScreenAnimationController <SBAppViewHostRequester> {
	SBDisplayItem *_activatingDisplayItem;
	SBAppView *_appView;
	SBOrientationTransformWrapperView *_appViewLayoutWrapper;
	SBAppSwitcherPageView *_animatingPageView;
	BOOL _isInteractive;
	BOOL _finishedSwitcherAnimation;
	BOOL _finishedCrossfadingToHostView;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
- (id)initWithTransitionContextProvider:(id)transitionContextProvider activatingDisplayItem:(id)item interactive:(BOOL)interactive;
- (id)_animationProgressDependencies;
- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (void)_crossfadeApp;
- (void)_evaluateDependenciesForCrossfadeStart;
- (id)_getTransitionWindow;
- (BOOL)_isActivatingFromContinuityApp;
- (void)_noteCrossfadeDidFinish;
- (void)_noteSwitcherAnimationFinished;
- (void)_prepareAnimation;
- (void)_reportAnimationFinishedIfNecessary;
- (void)_startAnimation;
- (id)appViewRequesterIdentifier:(id)identifier;
- (int)appViewRequesterPriority:(id)priority;
- (void)dealloc;
- (void)endTransitionWithSuccess:(BOOL)success completion:(id)completion;
- (void)setTransitionParameters:(UIEdgeInsets)parameters;
@end

