/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBUIAnimationLockScreenCameraToApp : SBUIAnimationDosidoTransitionController {
	SBLockScreenViewControllerBase *_lockscreenVC;
}
- (id)initWithActivatingApp:(id)activatingApp deactivatingLockscreen:(id)lockscreen;
- (void)_cleanupAnimation;
- (void)_prepareAnimation;
- (void)dealloc;
- (void)hideRealFromView;
@end

