/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationController.h"


__attribute__((visibility("hidden")))
@interface SBUIStarkScreenAnimationController : SBUIAnimationController {
	SBStarkScreenController *_starkScreenController;
}
@property(readonly, retain, nonatomic) SBStarkScreenController *starkScreenController;
- (id)initWithTransitionContextProvider:(id)transitionContextProvider starkScreenController:(id)controller;
- (void)__startAnimation;
- (id)__waitForAppActivationTransactionForApplication:(id)application;
- (BOOL)__wantsInitialProgressStateChange;
- (void)_cleanupAnimation;
- (id)_getTransitionWindow;
- (void)dealloc;
@end

