/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@interface SBVoiceMailAlertItem : SBDismissOnlyAlertItem {
	BOOL _isForVisualVoicemail;
	unsigned _recordUID;
}
+ (id)currentInstance;
+ (BOOL)hasCurrentInstance;
- (void)didDeactivateForReason:(int)reason;
- (BOOL)isForVisualVoicemail;
- (id)lockLabel;
- (void)performUnlockAction;
- (void)setIsVisualVoicemail:(BOOL)voicemail recordUID:(unsigned)uid;
- (BOOL)willShowInAwayItems;
@end

