/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIImageView.h>

@class UIImage;

@interface SBWallpaperView : UIImageView {
	int _orientation;
	UIImageView *_topGradient;
	UIImageView *_bottomGradient;
	BOOL _usesFilter;
	float _filterAlpha;
	float _gradientAlpha;
	CGRect _wallpaperContentsRect;
	UIImage *_uncomposedImage;
	UIImage *_portraitComposedImage;
	UIImage *_landscapeComposedImage;
}
@property(assign, nonatomic) float gradientAlpha;
@property(assign, nonatomic) int orientation;
+ (int)_desktopVariant;
+ (void)initialize;
+ (BOOL)lockScreenAndHomeScreenShareWallpaper;
+ (void)noteWallpaperPreferencesChanged;
- (id)initWithOrientation:(int)orientation;
- (void)_resetImage;
- (void)_setOrientation:(int)orientation duration:(double)duration force:(BOOL)force;
- (void)_setOrientationAnimationFinished;
- (void)_setUsesComposedImage:(BOOL)image createGradientsIfNeeded:(BOOL)needed;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (void)_wallpaperChanged;
- (float)alpha;
- (void)dealloc;
- (id)gradientImageForInterfaceOrientation:(int)interfaceOrientation;
- (void)replaceWallpaperWithImage:(id)image;
- (void)resetCurrentImageToWallpaper;
- (void)setAlpha:(float)alpha;
- (id)uncomposedImage;
- (CGRect)wallpaperContentsRect;
@end

