/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBWallpaperObserver <NSObject>
@optional
- (void)wallpaperDidChangeForVariant:(int)wallpaper;
- (void)wallpaperGeometryDidChangeForVariant:(int)wallpaperGeometry;
- (void)wallpaperLegibilitySettingsDidChange:(id)wallpaperLegibilitySettings forVariant:(int)variant;
- (void)wallpaperWillChangeForVariant:(int)wallpaper;
@end

