/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBWaveView : XXUnknownSuperclass {
	float _phaseWidth;
	float _phaseShift;
	float _minAmplitude;
	float _maxAmplitude;
	float _amplitude;
	float _levelDamping;
	double _phaseDuration;
	double _amplitudeChangeTime;
	double _amplitudeChangeDuration;
	float _lastAmplitude;
	float _level;
	BOOL _animating;
}
- (float)_amplitudeForLevel:(float)level;
- (float)_currentAmplitude;
- (void)_finishedAnimating;
- (float)_phaseShift;
- (void)_setAmplitude:(float)amplitude animated:(BOOL)animated;
- (void)beginAnimating;
- (void)setColor:(id)color;
- (void)setFrame:(CGRect)frame;
- (void)setLevel:(float)level animated:(BOOL)animated;
- (void)setLevelDamping:(float)damping;
- (void)setMaxAmplitude:(float)amplitude;
- (void)setMinAmplitude:(float)amplitude;
- (void)setPhaseAnimationDuration:(double)duration;
- (void)setPhaseShift:(float)shift;
- (void)setPhaseWidth:(float)width;
- (void)stopAnimating;
@end

