/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"

@class UIWebClip;

@interface SBWebApplicationIcon : SBApplicationIcon {
	UIWebClip *_webClip;
}
- (id)initWithApplication:(id)application;
- (id)_urlForLaunch;
- (BOOL)allowsUninstall;
- (BOOL)canGenerateGhostlyImageInBackground;
- (void)completeUninstall;
- (void)dealloc;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)generateIconImage:(int)image;
- (void)launch;
- (void)launchFromViewSwitcher;
- (BOOL)shouldEllipsizeLabel;
- (id)uninstallAlertBody;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertTitle;
- (id)webClip;
@end

