/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBWidgetHandlingNCColumnViewController : SBNCColumnViewController <SBWidgetHandling, SBWidgetViewControllerDelegate, SBNotificationCenterWidgetHost, NCWidgetDataSourceObserver, SBTodayViewSettingsViewControllerDelegate> {
	id<SBWidgetViewControllerDelegate> _widgetDelegate;
	NSMutableDictionary *_identifiersToWidgetSections;
	NSArray *_topLevelInterfaceItemIdentifierOrder;
	NSMutableSet *_defaultEnabledIDs;
	id _pendingVisibleWidgetCompletion;
	CGSize _cachedContentSize;
	id<SBWidgetHandlingNCColumnViewControllerDelegate> _delegate;
}
@property(readonly, copy) NSString *debugDescription;
@property(assign, nonatomic) id<SBWidgetHandlingNCColumnViewControllerDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(readonly, assign) Class superclass;
@property(readonly, assign, nonatomic) NSSet *visibleWidgetIDs;
@property(assign, nonatomic) id<SBWidgetViewControllerDelegate> widgetDelegate;
+ (id)interfaceItemForDatum:(id)datum fromDataSourceWithIdentifier:(id)identifier;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void)_enableWidgetsWithIdentifiers:(id)identifiers completion:(id)completion;
- (BOOL)_insertWidgetRowIfPossible:(id)possible;
- (void)_invalidate;
- (void)_invokeBlockWithAllWidgets:(id)allWidgets;
- (BOOL)_isWidgetWithIdentifierEnabled:(id)identifierEnabled;
- (id)_orderedEnabledInterfaceItems;
- (BOOL)_removeWidgetDatum:(id)datum;
- (BOOL)_removeWidgetRowIfPossible:(id)possible;
- (BOOL)_replaceWithWidgetDatum:(id)widgetDatum;
- (BOOL)_replaceWithWidgetRowIfPossible:(id)widgetRowIfPossible;
- (id)_representedGroup;
- (id)_sectionAfterSection:(id)section inCollection:(id)collection;
- (id)_sectionInfoForDatum:(id)datum;
- (void)_sortInterfaceItems:(id)items usingGuide:(id)guide;
- (id)_widgetHandlingBulletinViewController;
- (int)activeLayoutModeForWidget:(id)widget;
- (void)attemptReconnectionAfterUnanticipatedDisconnection:(id)disconnection;
- (BOOL)canRemoveViewOnDismissal:(id)dismissal;
- (void)contentAvailabilityDidChangeForWidget:(id)contentAvailability;
- (CGSize)contentSize;
- (void)dealloc;
- (void)enableAllWidgets:(id)widgets;
- (id)extensionForWidget:(id)widget;
- (void)hostDidDismiss;
- (void)hostDidPresent;
- (void)hostWillDismiss;
- (void)hostWillPresent;
- (void)insertAppropriateViewWithContent;
- (void)invalidateContentLayout;
- (void)invalidateDataAndRepopulateWithBlock:(id)block;
- (int)layoutModeForTodayViewSettingsViewController:(id)todayViewSettingsViewController;
- (void)makeVisibleWidgetWithIdentifier:(id)identifier animated:(BOOL)animated completion:(id)completion;
- (UIEdgeInsets)marginInsetsForWidget:(id)widget;
- (CGSize)maxSizeForWidget:(id)widget;
- (int)notificationCenterTableViewController:(id)controller insertionAnimationForRow:(id)row inSection:(id)section;
- (void)reloadSortOrder;
- (void)remoteViewControllerDidConnectForWidget:(id)remoteViewController;
- (BOOL)shouldRequestWidgetRemoteViewControllers;
- (void)sizeObservingView:(id)view didChangeSize:(CGSize)size;
- (Class)tableViewControllerClass;
- (void)todayViewSettingsViewController:(id)controller didReorderInterfaceItems:(id)items inGroup:(id)group;
- (id)todayViewSettingsViewController:(id)controller interfaceItemsForGroup:(id)group;
- (void)transitionToContentUnavailableViewIfNecessary;
- (void)updateWidgetsWithIdentifiers:(id)identifiers launchStats:(id)stats completion:(id)completion;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)view;
- (id)widget:(id)widget didUpdatePreferredHeight:(float)height completion:(id)completion;
- (void)widget:(id)widget requestsLaunchOfURL:(id)url;
- (void)widgetDataSource:(id)source removeDatum:(id)datum;
- (void)widgetDataSource:(id)source replaceWithDatum:(id)datum;
- (BOOL)widgetShouldAttemptReconnectionAfterUnanticipatedDisconnection:(id)widget;
- (id)widgetWithIdentifier:(id)identifier;
@end

