/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SBWidgetCell : XXUnknownSuperclass <SBModalLayoutCaching> {
	int _layoutMode;
	SBWidgetRowInfo *_representedWidgetRowInfo;
}
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int layoutMode;
@property(retain, nonatomic) SBWidgetRowInfo *representedWidgetRowInfo;
@property(readonly, assign) Class superclass;
- (id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
- (void)dealloc;
@end

