/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBWiFiManagerDelegate <NSObject>
@optional
- (void)dismiss;
- (void)wifiManager:(id)manager joinCompleted:(int)completed;
@required
- (void)wifiManager:(id)manager scanCompleted:(id)completed;
@end

