/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBWorkspaceTransitionContext.h"


__attribute__((visibility("hidden")))
@interface SBWorkspaceApplicationTransitionContext : SBWorkspaceTransitionContext {
	id _resultBlock;
	BOOL _background;
	BOOL _fencesAnimations;
	BOOL _alwaysRunsWatchdog;
	BOOL _waitsForSceneUpdates;
	BOOL _sentActivationResult;
	int _interfaceOrientation;
	int _preferredInterfaceOrientation;
}
@property(retain, nonatomic) SBWorkspaceApplication *activatingApplication;
@property(retain, nonatomic) SBWorkspaceEntity *activatingEntity;
@property(assign, nonatomic) BOOL alwaysRunsWatchdog;
@property(readonly, copy, nonatomic) NSSet *applications;
@property(assign, nonatomic, getter=isBackground) BOOL background;
@property(assign, nonatomic) BOOL fencesAnimations;
@property(assign, nonatomic) int interfaceOrientation;
@property(assign, nonatomic) int preferredInterfaceOrientation;
@property(readonly, copy, nonatomic) NSSet *previousApplications;
@property(copy, nonatomic) id resultBlock;
@property(assign, nonatomic) BOOL waitsForSceneUpdates;
- (id)init;
- (id)_display;
- (id)_realActivatingEntity;
- (double)_watchdogScaleFactorForApplication:(id)application;
- (id)applicationForBundleID:(id)bundleID;
- (id)applicationForLayoutRole:(int)layoutRole;
- (void)dealloc;
- (id)entityForLayoutRole:(int)layoutRole;
- (id)executionContextForApplication:(id)application;
- (void)finalize;
- (BOOL)hasSentActivationResult;
- (id)previousApplicationForBundleID:(id)bundleID;
- (id)previousApplicationForLayoutRole:(int)layoutRole;
- (id)previousEntityForLayoutRole:(int)layoutRole;
- (id)sceneClientSettingsForApplication:(id)application withSceneSettings:(id)sceneSettings;
- (id)sceneIdentifierForApplication:(id)application;
- (id)sceneSettingsForApplication:(id)application;
- (id)sceneTransitionContextForApplication:(id)application;
- (void)sendActivationResultErrorCode:(int)code;
- (void)setApplication:(id)application forLayoutRole:(int)layoutRole;
- (void)setEntity:(id)entity forLayoutRole:(int)layoutRole;
- (void)setPreviousEntity:(id)entity forLayoutRole:(int)layoutRole;
- (id)succinctDescriptionBuilder;
@end

