/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol UIDynamicItem <NSObject>
@property(readonly, assign, nonatomic) CGRect bounds;
@property(assign, nonatomic) CGPoint center;
@optional
@property(readonly, assign, nonatomic) UIBezierPath *collisionBoundingPath;
@property(readonly, assign, nonatomic) unsigned collisionBoundsType;
@required
@property(assign, nonatomic) CGAffineTransform transform;
@end

