/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol UIPrintStatusDelegate <NSObject>
- (void)printStatusViewController:(id)controller didDismissWithCancel:(BOOL)cancel;
@optional
- (void)printStatusViewControllerJobDidCancel:(id)printStatusViewControllerJob;
@end

